// Eurofabbro content - bilingual (IT/EN)
// All content extracted from the original base44 SPA bundle (https://eurofabbro-v1.base44.app)
// Image paths point to local /images/ assets

export const site = {
  name: "Eurofabbro",
  company: "Ferioli Sergio SRL",
  phone: "051 985300",
  phoneTel: "+39051985300",
  mobile: "347 4287776",
  mobileTel: "+393474287776",
  whatsapp: "393474287776",
  whatsappDisplay: "347 4287776",
  email: "eurofabbro@eurofabbro.com",
  address: "Via Galileo Galilei 140, 40014 Palata Pepoli di Crevalcore (BO)",
  hours: "Mon–Fri 8:00–18:00 · Sat by appointment",
  founded: 1977,
  logo: "/images/logo-landing.png",
  logoLanding: "/images/logo-landing.png",
  social: {
    facebook: "https://www.facebook.com/EUROFABBRO/",
    instagram: "https://www.instagram.com/eurofabbro/",
  },
} as const;

// Shared nav structure (labels translated per language)
const navItems = [
  { key: "lavorazioni", href: "/lavorazioni" },
  { key: "automazione", href: "/automazione" },
  { key: "percheNoi", href: "/perche-noi" },
  { key: "realizzazioni", href: "/realizzazioni" },
  { key: "detrazioni", href: "/detrazioni" },
] as const;

const navServices = [
  { key: "cancelli", href: "/cancelli" },
  { key: "inferriate", href: "/inferriate" },
  { key: "recinzioni", href: "/recinzioni" },
  { key: "carport", href: "/carport" },
  { key: "scale", href: "/scale" },
  { key: "balaustre", href: "/balaustre" },
  { key: "dehor", href: "/dehor" },
  { key: "arredi", href: "/arredi" },
  { key: "allarmi", href: "/allarmi" },
  { key: "manutenzione", href: "/manutenzione" },
  { key: "altreLavorazioni", href: "/lavorazioni" },
] as const;

const commonImages = {
  heroHome: "/images/053701002_generated_image.png",
  heroCancelli: "/images/eb6ff68c0_generated_image.png",
  heroInferriate: "/images/cfd8c4396_generated_image.png",
  heroRecinzioni: "/images/3cc2a0950_generated_image.png",
  heroLavorazioni: "/images/37ae1598f_generated_image.png",
  heroCarport: "/images/ff67b59d2_generated_image.png",
  heroAutomazione: "/images/1fd69a4bb_generated_image.png",
  heroPercheNoi: "/images/8b20c47b2_generated_image.png",
  heroRealizzazioni: "/images/196b11333_generated_image.png",
  heroDetrazioni: "/images/3ea644617_generated_image.png",
  turnkey1: "/images/2a8eed53a_generated_image.png",
  turnkey2: "/images/81e9c3696_generated_image.png",
  turnkey3: "/images/a18bfad4e_generated_image.png",
  carportSingle: "/images/28f664fa9_generated_image.png",
  carportDouble: "/images/9edc19b42_generated_image.png",
  carportIndustrial: "/images/190366ac2_generated_image.png",
  carportOutdoor: "/images/d5f42817e_generated_image.png",
  wp1: "/images/1.jpeg",
  wp2: "/images/2.jpeg",
  wp3: "/images/3.jpeg",
  wp4: "/images/4.jpg",
  wp5: "/images/5.jpg",
  wpCancelli: "/images/Cancelli-in-ferro-cento-1-300x225.jpg",
  wpCarpenteria: "/images/Carpenteria-metallica-su-misura-bologna-cento.jpg",
  wpGrate: "/images/Realizzazione-grate-in-ferro-bologna-480x360-1.jpg",
  wpStrutture: "/images/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg",
  wpParapetti: "/images/parapetti-per-balconi-1-300x225.jpg",
  wpDehor: "/images/Strutture-in-ferro-su-misura.jpg",
  wpArredi: "/images/Arredi-in-ferro-su-misura-bologna-1-300x225.jpg",
};

export const translations = {
  en: {
    lang: "en" as const,
    nav: {
      items: navItems,
      services: navServices,
      cta: { key: "cta", href: "/contatti" },
      label: {
        lavorazioni: "Products",
        automazione: "Automation",
        percheNoi: "Why Us",
        realizzazioni: "Portfolio",
        detrazioni: "Tax Deductions",
        contatti: "Contact",
        cta: "Request a Quote",
        cancelli: "Gates",
        inferriate: "Security Bars",
        recinzioni: "Fencing",
        carport: "Carports & Canopies",
        scale: "Iron Stairs",
        balaustre: "Railings & Balustrades",
        dehor: "Outdoor Dehor",
        arredi: "Iron Furniture",
        allarmi: "Alarm Systems",
        manutenzione: "Certified Maintenance",
        altreLavorazioni: "Other Works",
        close: "Close",
        menu: "Menu",
      },
    },
    hero: {
      badge: "Istituto Giordano Certified · CE",
      headlinePre: "Custom metalwork",
      headlineAccent: "certified",
      headlinePost: " — made to measure",
      subheadline: "Forty-nine years of ironwork in the Bologna province. In-house production, CE marking, guaranteed quality on every installation.",
      ctaPrimary: "Request a free quote",
      ctaSecondary: "Explore our work",
      cardEyebrow: "Ferioli Sergio · since 1977",
      cardBody: "Every gate, bar and fence is handcrafted in our workshop near Bologna and installed by our own team — from the first spark to the final bolt.",
      cornerMark: "Ferioli Sergio · Bologna · 1977",
      scroll: "Scroll",
      stats: [
        "1977–2026 · 49 Years of experience",
        "Istituto Giordano Certified",
        "Free quote within 24h",
      ],
    },
    certifications: {
      eyebrow: "Certifications & Guarantees",
      headline: "Certified ironwork you can trust",
      items: [
        {
          icon: "BadgeCheck",
          title: "Istituto Giordano Certified",
          sub: "First in Italy for manual and automatic gates",
        },
        {
          icon: "Shield",
          title: "CE Marking",
          sub: "On every gate, fence and security bar",
        },
        {
          icon: "Award",
          title: "60,000 openings tested",
          sub: "Verified durability over decades of use",
        },
        {
          icon: "Calendar",
          title: "Active since 1977",
          sub: "49 years of guaranteed in-house production",
        },
      ],
      certLabel: "All on Measure",
      certCaption: "4 simple operations · Custom metalwork",
      brochureAlt: "Tutto su Misura brochure — Ferioli Sergio & Co.",
      verified: "Verified",
      sealCaptions: [
        "Istituto Giordano",
        "CE Marking",
        "60,000 Aperture",
        "Since 1977",
        "Made in Italy",
        "In-house production",
      ],
      footerLine: "Ferioli Sergio & Co. · Bologna · Since 1977",
      stats: [
        { value: "49", label: "Years active" },
        { value: "60k", label: "Openings tested" },
        { value: "100%", label: "Made in Italy" },
        { value: "100%", label: "In-house production" },
      ],
    },
    turnkey: {
      preLabel: "Valore Plus by Ferioli",
      headlinePre: "Valore Plus — Ferioli's ",
      headlineAccent: "turnkey service",
      headlinePost: "",
      subheadline: "From design to installation: we take care of everything.",
      cards: [
        { title: "Design", text: "Site visit, measurements and bespoke project. We study every detail based on your space, style and current regulations.", image: commonImages.turnkey1 },
        { title: "Paperwork", text: "We assist you in managing technical documentation and necessary paperwork — you don't have to worry about it.", image: commonImages.turnkey2 },
        { title: "Build & Install", text: "We produce and install directly, without intermediaries. From our workshop to your home, with a single point of contact.", image: commonImages.turnkey3 },
      ],
      closing: '"A single point of contact, from the first call to the installed gate."',
    },
    products: {
      preLabel: "What we make",
      headlinePre: "Everything you can craft in ",
      headlineAccent: "iron",
      subheadline: "From design to installation, every project is produced in-house. Free quotes, guaranteed delivery.",
      viewAll: "View all products",
      learnMore: "Learn more",
      items: [
        { name: "Gates & Access", desc: "Custom protected access for your property. Sliding, swing, pedestrian and automated gates.", icon: "DoorOpen", link: "/cancelli" },
        { name: "Security Bars", desc: "Protection for windows and doors without sacrificing aesthetics or natural light.", icon: "Grid3x3", link: "/inferriate" },
        { name: "Fencing", desc: "Secure and decorative perimeter in wrought iron or modular slats for every need.", icon: "Fence", link: "/recinzioni" },
        { name: "Iron Stairs", desc: "Custom stairs for indoors and outdoors, residential and industrial, built to last.", icon: "TrendingUp", link: "/lavorazioni#scale" },
        { name: "Carports & Canopies", desc: "Custom self-supporting iron structures to protect vehicles from the elements.", icon: "CarFront", link: "/carport" },
        { name: "Automation", desc: "Comfort and security with automation systems for gates and shutters.", icon: "Settings", link: "/automazione" },
      ],
    },
    authority: {
      preLabel: "Why choose Eurofabbro",
      headlinePre: "The only ",
      headlineAccent: "certified",
      headlinePost: " metalworks in the area",
      body: "Thanks to Istituto Giordano certification — a technical body founded in 1959 — our gates are tested for 60,000 openings and CE marked. We are the trusted reference for certified metalwork between Bologna and Cento.",
      certBadge: "Istituto Giordano Certified · CE Marking",
      stats: [
        { number: "49", label: "Years in business (1977–2026)" },
        { number: "60,000", label: "Openings tested for CE marking" },
        { number: "100%", label: "In-house custom production" },
        { number: "24h", label: "To receive your quote" },
      ],
    },
    process: {
      preLabel: "Our process",
      headlinePre: "From ",
      headlineAccent: "request",
      headlinePost: " to installation",
      steps: [
        { title: "1. Contact us", desc: "Call, WhatsApp or fill the form. We'll respond within 24 hours to schedule a free site visit.", icon: "MessageCircle" },
        { title: "2. Survey & design", desc: "We visit, measure and design the bespoke solution. You receive a detailed, no-obligation quote.", icon: "Ruler" },
        { title: "3. Production & install", desc: "We produce in-house and install. We guarantee the work and remain available for any post-installation need.", icon: "CircleCheckBig" },
      ],
    },
    featuredProjects: {
      preLabel: "Our work",
      headlinePre: "Every ",
      headlineAccent: "project",
      headlinePost: " tells a story",
      viewAll: "View all projects",
      projects: [
        { name: "Self-supporting Gate", location: "Bologna", image: commonImages.wp1, link: "/cancelli", span: 2 },
        { name: "Security Bars", location: "Cento (FE)", image: commonImages.wp5, link: "/inferriate" },
        { name: "Stairs & Structures", location: "Crevalcore (BO)", image: commonImages.wpStrutture, link: "/lavorazioni" },
        { name: "Swing Gate", location: "San Giovanni in Persiceto (BO)", image: commonImages.wp2, link: "/cancelli" },
        { name: "Custom Fencing", location: "Massa Finalese (MO)", image: commonImages.wpCancelli, link: "/recinzioni" },
        { name: "Anti-burglar Grilles", location: "Bologna", image: commonImages.wpGrate, link: "/inferriate" },
      ],
    },
    deductionBanner: {
      headlinePre: "Save up to ",
      headlineAccent: "50%",
      headlinePost: " with tax deductions",
      body: "The Security Bonus lets you deduct 36% of expenses for gates, security bars and alarm systems. With tax deductions it reaches 50%. Subsidised financing with Compass, 24 to 48 month plans.",
      cta: "Discover how to save",
      badges: ["Security Bonus 36%", "Tax Deductions 50%", "Compass 24/36/48 months"],
    },
    workWithUs: {
      preLabel: "Work with us",
      headlinePre: "Looking for ",
      headlineAccent: "partners",
      headlinePost: " and professionals",
      subheadline: "Join our network. We are always looking for installers, resellers, and qualified professionals.",
      cta: "Learn more",
      ctaHref: "/landing/lavora-con-noi",
    },
    testimonials: {
      preLabel: "What clients say",
      headlinePre: "The ",
      headlineAccent: "trust",
      headlinePost: " of our clients",
      items: [
        { quote: "Impeccable work on our sliding gate. Professional, punctual, and the result exceeded expectations. Highly recommended.", name: "Marco R.", location: "Crevalcore (BO)", rating: 5 },
        { quote: "We had security bars fitted throughout the house. Excellent quality, quick installation and clean worksite. Very satisfied.", name: "Laura B.", location: "Cento (FE)", rating: 5 },
        { quote: "We relied on Ferioli for our warehouse fencing. Fair price, solid and lasting work. We recommend them without reservation.", name: "Giovanni P.", location: "San Giovanni in Persiceto (BO)", rating: 5 },
      ],
    },
    faq: {
      title: "Frequently Asked Questions",
      items: [
        { q: "Do you work in all of Bologna province?", a: "Yes, we operate in Bologna, Modena and Ferrara provinces with direct site visits and installations." },
        { q: "How long does a custom gate take?", a: "On average 3–6 weeks from quote confirmation, depending on the complexity of the project." },
        { q: "Do you offer financing?", a: "Yes, we partner with Compass to offer subsidised instalment plans from 24 to 48 months." },
        { q: "Are your products CE marked?", a: "Yes, we are certified by Istituto Giordano — our gates are tested for 60,000 openings and CE marked." },
        { q: "Do you handle paperwork and permits?", a: "Yes, our Valore Plus service includes paperwork and permits management, so you don't have to worry." },
        { q: "Do you produce everything in-house?", a: "Yes, we design, produce and install directly, with no intermediaries." },
      ],
    },
    cta: {
      preLabel: "Start today",
      headlinePre: "Request your free ",
      headlineAccent: "quote",
      subheadline: "Free site visit, no-obligation quote. We respond within 24 hours.",
      btnForm: "Fill the form",
      btnWhatsapp: "WhatsApp us",
      btnPhone: "051 985300",
      chip: "Contact",
      primary: "Request a quote",
      whatsappPre: "Chat on",
      reassurance: ["Response within 24 hours", "Free site visit", "No-obligation quote"],
    },
    lavorazioni: {
      hero: {
        headlinePre: "Other iron ",
        headlineAccent: "works",
        subheadline: "Stairs, balustrades, carports, commercial dehors and iron furniture. Every project is designed to measure for your needs.",
        cta: "Request your quote",
      },
      sections: [
        { id: "scale", name: "Iron Stairs", desc: "We design and build custom iron stairs for indoors and outdoors, residential and industrial. Straight, with landing, metal structure — combinable with wood, glass or other materials.", image: commonImages.wpStrutture, href: "/scale" },
        { id: "balustre", name: "Balustrades & Railings", desc: "Custom balustrades and railings for balconies, stairs and terraces, compliant with safety regulations. Galvanised for long life.", image: commonImages.wpParapetti, href: "/balaustre" },
        { id: "carport", name: "Carports & Canopies", desc: "Custom iron carports: self-supporting canopies to protect vehicles from the elements. Customisable and galvanised for maximum resistance.", image: commonImages.carportSingle, href: "/carport" },
        { id: "dehor", name: "Commercial Dehors", desc: "Custom iron dehors for bars, restaurants and commercial activities. Resistant, elegant and fully customisable structures, compliant with local regulations.", image: commonImages.wpDehor, href: "/dehor" },
        { id: "arredi", name: "Iron Furniture", desc: "Industrial and residential iron furniture: shelving, workbenches, beds, cabinets, bathroom fittings, bookcases. Everything 100% custom-made.", image: commonImages.wpArredi, href: "/arredi" },
      ],
    },
    carport: {
      hero: {
        headlinePre: "Custom iron ",
        headlineAccent: "carports & canopies",
        subheadline: "We design and build custom iron carports and canopies to protect your vehicles from the elements. Self-supporting structures, galvanised and paintable on request.",
        cta: "Request your quote",
      },
      introTitlePre: "Tailored protection for ", introTitleAccent: "your vehicles",
      introBody: "An iron carport is the ideal solution for protecting your vehicle from the elements without sacrificing aesthetics. Compared to a traditional garage, it takes up less space, costs less and integrates perfectly with your garden or driveway. Every structure is designed to measure, built in our workshop and installed directly by us.",
      featuresTitlePre: "Why choose an iron ", featuresTitleAccent: "carport",
      features: ["Self-supporting structure, no intermediate pillars", "Hot-dip galvanisation for maximum weather resistance", "Fully customisable in size, shape and finish", "Suitable for residential and industrial use", "Compatible with solar panels", "Minimal maintenance over time", "In-house production and direct installation", "Free quote within 24h"],
      typesTitlePre: "Types of ", typesTitleAccent: "covers",
      types: [
        { name: "Single carport", desc: "Cover for a single vehicle, ideal for private homes with a driveway. Clean design integrated with existing architecture. Available in various widths and heights.", image: commonImages.carportSingle },
        { name: "Double carport", desc: "Solution for two or more vehicles, perfect for families or small businesses. Robust structure with ample usable space. Option to add side panels or enclosures.", image: commonImages.carportDouble },
        { name: "Industrial canopies", desc: "Custom covers for businesses, warehouses and loading/unloading areas. High resistance and guaranteed long life. Ideal for large surfaces with high structural loads.", image: commonImages.carportIndustrial },
        { name: "Outdoor canopies", desc: "Protection for entrances, terraces and outdoor areas. Elegant, customisable and weather-resistant. Also perfect for camper or motorcycle parking areas.", image: commonImages.carportOutdoor },
      ],
      materialsTitlePre: "Materials and ", materialsTitleAccent: "finishes",
      materials: [
        { name: "Hot-dip galvanised steel", desc: "Hot-dip galvanisation provides maximum protection against rust and weathering, with a lifespan exceeding 20 years with no maintenance." },
        { name: "Powder coating", desc: "Available in any RAL colour. Powder coating offers excellent resistance to impact and UV rays, keeping the colour unchanged over time." },
        { name: "Polycarbonate roofing", desc: "Transparent or translucent panels that allow natural light through while protecting from rain. Lightweight, resistant and insulating." },
        { name: "Corrugated sheeting", desc: "A cost-effective and robust solution for opaque roofing. High mechanical resistance and long-lasting waterproofing." },
      ],
      faq: [
        { q: "How much does a custom iron carport cost?", a: "The cost depends on dimensions, roofing type and chosen finishes. After a free site visit we provide a detailed, no-obligation quote." },
        { q: "Do I need planning permission for a carport?", a: "It depends on the dimensions and local regulations. For smaller structures a simplified notification is often sufficient. We assist you with the process." },
        { q: "How long does it take to build and install?", a: "Timelines depend on project complexity. On average, from quote confirmation to installation it takes 3–6 weeks." },
        { q: "Are carports compatible with solar panels?", a: "Yes, we design structures to accommodate photovoltaic panels, optimising the frame sizing for the additional load." },
        { q: "Which areas do you cover?", a: "We operate in Bologna and Modena provinces with direct site visits and installations." },
      ],
    },
    realizzazioni: {
      hero: {
        headlinePre: "Our ",
        headlineAccent: "portfolio",
        subheadline: "Every project tells a story of artisan quality, attention to detail and client satisfaction.",
        cta: "Request your quote",
      },
      projects: [
        { name: "Sliding Gate", location: "Bologna", type: "Gate", image: commonImages.wpCarpenteria, link: "/cancelli" },
        { name: "Swing Gate", location: "Cento (FE)", type: "Gate", image: commonImages.wp2, link: "/cancelli" },
        { name: "Fencing", location: "Massa Finalese (MO)", type: "Fence", image: commonImages.wpCancelli, link: "/recinzioni" },
        { name: "Internal Stairs", location: "Bologna", type: "Structure", image: commonImages.wp4, link: "/lavorazioni" },
        { name: "Security Bars", location: "Crevalcore (BO)", type: "Security Bars", image: commonImages.wpGrate, link: "/inferriate" },
        { name: "External Stairs", location: "San Giovanni in Persiceto (BO)", type: "Structure", image: commonImages.wpStrutture, link: "/lavorazioni" },
        { name: "Balustrades", location: "Bologna", type: "Railing", image: commonImages.wpParapetti, link: "/lavorazioni" },
        { name: "Custom Furniture", location: "Cento (FE)", type: "Furniture", image: commonImages.wpArredi, link: "/lavorazioni" },
        { name: "Commercial Dehors", location: "Bologna", type: "Structure", image: commonImages.wpDehor, link: "/lavorazioni" },
        { name: "Sheet Metal Gate", location: "Crevalcore (BO)", type: "Gate", image: commonImages.wp3, link: "/cancelli" },
      ],
    },
    detrazioni: {
      hero: {
        headlinePre: "Save up to ",
        headlineAccent: "50%",
        headlinePost: " with tax deductions",
        subheadline: "2026 tax deductions for gates, security bars and alarm systems. The right time to invest.",
        cta: "Request information",
      },
      bonusTitlePre: "Security Bonus and ", bonusTitleAccent: "Renovation Bonus", bonusTitlePost: "",
      bonusBody: "In 2026, tax relief is still available for improvements to property security. Work on gates, security bars, fencing and access control can qualify for security and renovation tax deductions.",
      eligibleTitlePre: "Which work may be ", eligibleTitleAccent: "deductible", eligibleTitlePost: "",
      eligible: ["Installation of security bars", "Installation or replacement of gates", "Gate automation", "Fencing and access control systems", "Burglar alarms and CCTV"],
      compassTitlePre: "Financing and payment ", compassTitleAccent: "options", compassTitlePost: "",
      compassBody: "To facilitate the project, we offer financing with customised instalment plans of 24, 36 or 48 months, so you can install immediately without sacrificing quality.",
      calcTitlePre: "Calculate your ", calcTitleAccent: "savings", calcTitlePost: "",
      calcLabel: "Estimated project value (€)",
      calcPlaceholder: "e.g. 5000",
      calcResult36: "With Security Bonus (36%)",
      calcResult50: "With Tax Deductions (50%)",
      calcSave: "You save",
      faq: [
        { q: "Which products qualify for deductions?", a: "Gates, security bars, alarms, CCTV and all work that improves property security." },
        { q: "How do you claim the deduction?", a: "Payment must be made via a 'speaking' bank transfer and documentation retained. Our consultants can guide you." },
        { q: "Can the work be financed?", a: "Yes, we offer Compass instalment plans from 24 to 48 months to make the investment accessible." },
        { q: "Are security bars always deductible?", a: "Yes, bar installation qualifies as a security improvement and is tax deductible for both new and replacement installations." },
      ],
    },
    contatti: {
      headlinePre: "We're just ",
      headlineAccent: "around the corner",
      detailsTitle: "Our details",
      requestTitle: "Send a request",
      contactLabels: {
        phone: "Phone",
        whatsapp: "WhatsApp",
        email: "Email",
        address: "Address",
        hours: "Hours",
      },
      processTitle: "What happens after you contact us",
      processSteps: ["We respond within 24h", "Free site visit", "No-obligation quote"],
      form: {
        name: "Full name *",
        phone: "Phone *",
        email: "Email",
        type: "Type of work",
        typeOptions: ["-- Select --", "Gate", "Security Bars", "Fencing", "Stairs", "Alarm", "Automation", "Other"],
        message: "Message",
        privacy: "I accept the privacy policy and data processing *",
        submit: "Send request",
        success: "Request sent successfully! We'll contact you within 24 hours.",
        error: "An error occurred. Please try again or call us directly.",
      },
    },
    footer: {
      tagline: "Certified metalwork since 1977.",
      colLavorazioni: "Products",
      colContatti: "Contact",
      colCertificazioni: "Certifications",
      certText: "Istituto Giordano Certified · CE Marking",
      compassText: "Compass financing available",
      copyright: "© 2024 Ferioli Sergio SRL",
      privacy: "Privacy Policy",
      cookie: "Cookie preferences",
      piva: "VAT IT02128491202",
    },
    form: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      message: "How can we help?",
      privacy: "By submitting you accept the",
      privacyLink: "privacy policy",
      send: "Send request",
      sent: "Request sent",
      success: "Thanks! We'll get back to you within 24 hours.",
      error: "Something went wrong. Please call us directly.",
    },
    common: {
      learnMore: "Learn more",
      readMore: "Read more",
      requestQuote: "Request your quote",
      viewAll: "View all",
      callUs: "Call {phone}",
      whatsappLabel: "WhatsApp: {display}",
    },
    pageLabels: {
      tipologie: "Types",
      benefici: "Benefits",
      material: "Material",
      modular: "Modular",
      intro: "Intro",
      why: "Why us",
      catalog: "Catalog",
      materials: "Materials",
      bonus: "Bonus",
      eligible: "Eligible",
      financing: "Financing",
      process: "Process",
      reach: "Reach us",
      write: "Write us",
      heritage: "Heritage",
      howItWorks: "How it works",
      types: "Types",
      controls: "Controls",
      service: "Service",
      apply: "Apply",
      getInTouch: "Get in touch",
      project: "Tell us about your project",
      quote24: "We respond within 24 hours with a no-obligation quote.",
      ctaTitle: "Request your free quote",
      partners: "Installers, resellers, architects, construction companies.",
      gutters: ["Gates & Fencing · Bologna", "Work with us · Bologna, Italy"],
    },
    cancelli: {
      hero: {
        headlinePre: "Custom iron ",
        headlineAccent: "gates",
        subheadline: "Sliding, swing, pedestrian and self-supporting gates. Designed, built and installed in-house. Istituto Giordano certified, CE marked.",
        cta: "Request a free quote",
      },
      variantsTitlePre: "Every type, ",
      variantsTitleAccent: "every opening",
      variantsTitlePost: "",
      variants: [
        { name: "Sliding gates", desc: "Ideal for narrow driveways and limited space. Quiet, reliable, tested for over 60,000 openings.", href: "/cancelli/scorrevole" },
        { name: "Swing gates", desc: "Single or double leaf, traditional or designer. Manual or automated, hot-dip galvanised on request.", href: "/cancelli/battente" },
        { name: "Pedestrian gates", desc: "Matching the main gate in style, material and finish. Perfect for daily access.", href: "/cancelli/pedonali" },
        { name: "Self-supporting gates", desc: "No ground rail: ideal for uneven driveways, snow and gravel. Clean, silent, robust.", href: "/cancelli/autoportanti" },
      ],
      galleryEyebrow: "Types in our workshop",
      galleryTitlePre: "Every ",
      galleryTitleAccent: "opening",
      galleryTitlePost: ", a solution",
      galleryItems: [
        { label: "Sliding" },
        { label: "Swing" },
        { label: "Pedestrian" },
        { label: "Self-supporting" },
      ],
      certStripTitle: "Istituto Giordano Certified",
      certStripSub: "CE Marking · Tested for 60,000 openings",
      whyTitlePre: "Why a Ferioli Sergio ",
      whyTitleAccent: "gate",
      whyBenefits: [
        "Istituto Giordano certified — first in Italy for manual and automatic gates",
        "60,000 openings tested on every certified model",
        "Hot-dip galvanising and powder coating on request",
        "100% in-house production, direct installation by our team",
        "CE marking and full technical documentation",
        "Tax deductible under Security Bonus 50%",
      ],
      prontaTitlePre: "A gate that is ",
      prontaTitleAccent: "ready to install",
      prontaBody: "We deliver finished, certified gates, with installation by our own team. No intermediaries, no surprises, no off-the-shelf solutions.",
      faq: [
        { q: "How long does it take to build a custom gate?", a: "On average 4 to 6 weeks from the site visit, depending on the design, size and finish. We confirm a precise timeline in the quote." },
        { q: "Do you also automate existing gates?", a: "Yes. We retrofit existing manual gates (our own or third-party) with motors, control electronics and CE-compliant safety devices." },
        { q: "What warranty do you offer on your gates?", a: "Every Ferioli Sergio gate is covered by a 10-year structural warranty on the frame and a 24-month warranty on motors and electronics." },
        { q: "Do you handle the paperwork for tax deductions?", a: "Yes. We provide the technical documentation, conformity declaration and invoice with the right details to access the Bonus Sicurezza 50%." },
      ],
    },
    inferriate: {
      hero: {
        headlinePre: "Security ",
        headlineAccent: "bars",
        subheadline: "Fixed, opening, folding and double-leaf security bars. In-house production, CE marked, tailored to your windows and doors.",
        cta: "Request a free quote",
      },
      variantsTitlePre: "Every type",
      variantsTitleAccent: " for every opening",
      variantsTitlePost: "",
      variants: [
        { name: "Fixed bars", desc: "Sturdy and maintenance-free. Ideal for ground floor windows and openings that don't need to open.", href: "/inferriate/fisse" },
        { name: "Opening bars", desc: "One or two leaves, side or top opening. Safe and easy to use, with a key-operated lock.", href: "/inferriate/apribili" },
        { name: "Folding bars", desc: "Book-style opening, ideal for large French windows and shop windows. Compact, elegant, secure.", href: "/inferriate/snodabili" },
        { name: "Double-leaf bars", desc: "For large openings: classic two-leaf hinge, with a single central lock. Maximum security, classic look.", href: "/inferriate/due-ante" },
      ],
      galleryEyebrow: "Types in our workshop",
      galleryTitlePre: "Security ",
      galleryTitleAccent: "for every opening",
      galleryItems: [
        { label: "Fixed" },
        { label: "Opening" },
        { label: "Folding" },
        { label: "Double-leaf" },
      ],
      benefitsTitlePre: "Security that ",
      benefitsTitleAccent: "blends in",
      benefitsTitlePost: " with your home",
      benefits: [
        "Designed to measure on your windows and doors",
        "Galvanised and painted on request, wide colour range",
        "Internal release and child-safe locks",
        "Compatible with burglar alarms and home automation",
        "CE marking and EN 1627 resistance class certification",
        "Tax deductible under Security Bonus 50%",
      ],
      faq: [
        { q: "Are security bars safe in case of emergency?", a: "Yes. Every opening bar has a quick-release mechanism from the inside, no key needed. You can get out in a few seconds." },
        { q: "Do they need maintenance?", a: "Hot-dip galvanised and powder-coated bars are maintenance-free. We recommend a yearly visual check on hinges and locks." },
        { q: "Can I match the bars to the colour of my shutters?", a: "Of course. We offer a wide range of RAL colours and finishes to match your existing fixtures." },
        { q: "Do you also install bars on French windows?", a: "Yes. Folding bars are designed for large openings. We also make bespoke solutions for sliding doors and arched windows." },
      ],
    },
    recinzioni: {
      hero: {
        headlinePre: "Custom ",
        headlineAccent: "fencing",
        subheadline: "Modular slats, metal mesh, decorative and security fencing. In-house design, hot-dip galvanising on request, CE marked.",
        cta: "Request a free quote",
      },
      ironTitlePre: "Iron, mesh and ",
      ironTitleAccent: "modular slats",
      ironBody: "From decorative iron fencing for villas to modular slat systems for industrial sites: we design and build the right fencing for every need, with hot-dip galvanising and powder coating on request.",
      benefits: [
        "Hot-dip galvanised and powder coated",
        "Modular slats, mesh and decorative iron",
        "Custom design, in-house production",
        "Posts, gates and accessories in matching finish",
      ],
      galleryEyebrow: "Types in our workshop",
      galleryTitlePre: "Slats, mesh",
      galleryTitleAccent: " and custom modules",
      galleryItems: [
        { label: "Modular iron" },
        { label: "Metal mesh" },
        { label: "Decorative mesh" },
        { label: "Decorative" },
      ],
      faq: [
        { q: "Which fencing is best for a private home?", a: "For residential properties we typically recommend decorative iron fencing or modular slat systems. We assess style, height and intended use during the site visit." },
        { q: "Do you also install gates matching the fencing?", a: "Yes. We make pedestrian and driveway gates in the same material and finish as the fencing, for a consistent look." },
        { q: "How long does installation take?", a: "For a typical 30-linear-metre fence, installation takes 2 to 4 days, plus 4 to 6 weeks for custom production." },
        { q: "Do you handle the foundations?", a: "Yes. Our team takes care of post foundations, plinths and any groundwork required, for a turnkey delivery." },
      ],
    },
    automazione: {
      hero: {
        headlinePre: "Gate ",
        headlineAccent: "automation",
        headlinePost: " systems",
        subheadline: "We design, install and service automation for gates, doors and shutters. Control via remote, smartphone, keypad and home automation.",
        cta: "Request consultation",
      },
      howTitlePre: "How ",
      howTitleAccent: "we work",
      howTitlePost: " on automation",
      howBody: "Every automation project starts with a site visit. We assess space, weight, frequency of use and your preferred control method. Then we propose the right motor, accessories and safety devices for full EN 12453 compliance.",
      typesTitlePre: "Types",
      typesTitleAccent: " of automation",
      typesTitlePost: "",
      typesBody: "Automation for sliding, swing, pedestrian and self-supporting gates. In-house design, branded motors, CE marking, post-install assistance.",
      types: [
        { name: "Sliding motors", desc: "Quiet operation, soft start and stop, 100% duty cycle, tested for over 60,000 openings." },
        { name: "Underground motors", desc: "Hidden drive for a clean look. Designed for swing gates up to 4m and 800kg per leaf." },
        { name: "Articulated arms", desc: "For pivot and large-leaf swing gates. Robust, reliable, ideal for residential and industrial use." },
      ],
      controlsTitle: "Ways to control your gate",
      controls: [
        "Remote control",
        "Keypad & intercom",
        "Smartphone app",
        "Sensors and safety",
      ],
      serviceTitlePre: "A single ",
      serviceTitleAccent: "point of contact",
      serviceTitlePost: " for your automation",
      serviceBody: "From design to installation, from warranty to scheduled maintenance: we are your only partner for gate and shutter automation. CE marked, certified, supported.",
    },
    percheNoi: {
      hero: {
        headlinePre: "Forty-nine years ",
        headlineAccent: "of iron",
        headlinePost: " — by hand",
        subheadline: "Three generations of the Ferioli Sergio family have been handcrafting iron in our workshop near Bologna since 1977. Every gate, bar and fence is born here.",
        cta: "Discover our workshop",
      },
      storyTitlePre: "Our story, our ",
      storyTitleAccent: "workshop",
      storyTitlePost: "",
      storyBody: "Founded in 1977 in Palata Pepoli di Crevalcore, our workshop has grown from a one-man operation to a team of 12 specialised artisans. We work iron like it used to be worked: by hand, with modern tools but the same care.",
      guaranteeTitlePre: "Certified work, ",
      guaranteeTitleAccent: "guaranteed",
      guaranteeTitlePost: " over time",
      guaranteeBody: "Every Ferioli Sergio product carries our company name and is covered by a 10-year structural warranty. We are on the field for installation, scheduled maintenance and post-installation service.",
      highlights: [
        "49 years of artisan experience",
        "First in Italy CE certified (Istituto Giordano)",
        "In-house production, direct installation",
      ],
      workshopCards: [
        { label: "Workshop", alt: "Ferioli Sergio workshop — work benches" },
        { label: "Warehouse", alt: "Industrial shelving and warehouse" },
        { label: "Production", alt: "Custom iron products in production" },
      ],
    },
    landings: {
      cancelliRecinzioni: {
        heroEyebrow: "Gates & Fencing · Bologna",
        heroTitlePre: "Custom iron ",
        heroTitleAccent: "gates and fencing",
        heroSub: "Production and installation of custom iron gates and fencing. 49 years of experience, CE marking, free site visit in Bologna and Modena.",
        heroCta: "Request a quote",
        benefitsTitle: "Why choose us",
        benefits: [
          "Free site visit within 24h",
          "Custom design, in-house production",
          "Hot-dip galvanising and painting on request",
          "CE marking and full technical documentation",
          "Direct installation by our team",
          "Tax deductible under Security Bonus 50%",
        ],
        certTitle: "First in Italy, certified",
        certBody: "Istituto Giordano certification, CE marking on every installation.",
        requestEyebrow: "Request",
      },
      lavoraConNoi: {
        heroEyebrow: "Work with us · Bologna",
        heroTitlePre: "Partner with ",
        heroTitleAccent: "Ferioli Sergio",
        heroSub: "We are always looking for installers, resellers, architects and qualified professionals. Join our network of trusted partners.",
        heroCta: "Send your application",
        benefitsTitle: "Who we work with",
        benefits: [
          "Installers and fitters",
          "Resellers and showrooms",
          "Architects and engineers",
          "Construction companies",
        ],
        certTitle: "49 years of qualified experience",
        certBody: "Istituto Giordano certified, CE marking, in-house production. Quality you can build a business on.",
        requestEyebrow: "Apply",
      },
    },
    wppage: {
      fallbackTitle: "Page not available",
      fallbackBody: "Content not found for: {slug}",
      galleryEyebrow: "Portfolio",
      galleryTitlePre: "Other ",
      galleryTitleAccent: "custom works",
      relatedTitle: "Learn more",
    },
    notFound: {
      title: "Page not found",
      body: "The page you are looking for doesn't exist or has been moved. Get back on track from here.",
      ctaHome: "Back to home",
    },
    grazie: {
      eyebrow: "Message received",
      titlePre: "Thanks for",
      titleAccent: "reaching out",
      body: "We've received your request. Our staff will get back to you shortly.",
      ctaHome: "Back to home",
    },
  },

  it: {
    lang: "it" as const,
    nav: {
      items: navItems,
      services: navServices,
      cta: { key: "cta", href: "/contatti" },
      label: {
        lavorazioni: "Lavorazioni",
        automazione: "Automazione",
        percheNoi: "Perché noi",
        realizzazioni: "Realizzazioni",
        detrazioni: "Detrazioni",
        contatti: "Contatti",
        cta: "Richiedi preventivo",
        cancelli: "Cancelli",
        inferriate: "Inferriate",
        recinzioni: "Recinzioni",
        carport: "Carport e Tettoie",
        scale: "Scale in ferro",
        balaustre: "Balaustre e ringhiere",
        dehor: "Dehor",
        arredi: "Arredi in ferro",
        allarmi: "Allarmi e videosorveglianza",
        manutenzione: "Carpenteria certificata",
        altreLavorazioni: "Altre lavorazioni",
        close: "Chiudi",
        menu: "Menu",
      },
    },
    hero: {
      badge: "Certificati Istituto Giordano · CE",
      headlinePre: "Carpenteria metallica",
      headlineAccent: "certificata",
      headlinePost: " — su misura",
      subheadline: "Quarantanove anni di lavorazioni in ferro nella provincia di Bologna. Produzione interna, marcatura CE, garanzia su ogni installazione.",
      ctaPrimary: "Richiedi preventivo gratuito",
      ctaSecondary: "Scopri le lavorazioni",
      cardEyebrow: "Ferioli Sergio · dal 1977",
      cardBody: "Ogni cancello, inferriata e recinzione è lavorato a mano nella nostra officina vicino Bologna e installato dal nostro team — dalla prima scintilla all'ultimo bullone.",
      cornerMark: "Ferioli Sergio · Bologna · 1977",
      scroll: "Scorri",
      stats: [
        "1977–2026 · 49 Anni di esperienza",
        "Certificati Istituto Giordano",
        "Preventivo gratuito in 24h",
      ],
    },
    certifications: {
      eyebrow: "Certificazioni e garanzie",
      headline: "Carpenteria certificata di cui ti puoi fidare",
      items: [
        {
          icon: "BadgeCheck",
          title: "Certificati Istituto Giordano",
          sub: "Primi in Italia per cancelli manuali e automatici",
        },
        {
          icon: "Shield",
          title: "Marcatura CE",
          sub: "Su ogni cancello, recinzione e inferriata",
        },
        {
          icon: "Award",
          title: "60.000 aperture testate",
          sub: "Durata verificata per decenni di utilizzo",
        },
        {
          icon: "Calendar",
          title: "Attivi dal 1977",
          sub: "49 anni di produzione interna garantita",
        },
      ],
      certLabel: "Tutto su Misura",
      certCaption: "4 semplici operazioni · Carpenteria su misura",
      brochureAlt: "Brochure Tutto su Misura — Ferioli Sergio & C. S.n.c.",
      verified: "Verificato",
      sealCaptions: [
        "Istituto Giordano",
        "Marcatura CE",
        "60.000 Aperture",
        "Dal 1977",
        "Made in Italy",
        "Produzione interna",
      ],
      footerLine: "Ferioli Sergio & C. S.n.c. · Bologna · 1977",
      stats: [
        { value: "49", label: "Anni di attività" },
        { value: "60k", label: "Aperture testate" },
        { value: "100%", label: "Made in Italy" },
        { value: "100%", label: "Produzione interna" },
      ],
    },
    turnkey: {
      preLabel: "Valore Plus by Ferioli",
      headlinePre: "Valore Plus — ",
      headlineAccent: "Il servizio chiavi in mano",
      headlinePost: " di Ferioli",
      subheadline: "Dalla progettazione alla posa: pensiamo a tutto noi.",
      cards: [
        { title: "Progettazione", text: "Sopralluogo, misure e progetto su misura. Studiamo ogni dettaglio in base al tuo spazio, al tuo stile e alle normative vigenti.", image: commonImages.turnkey1 },
        { title: "Pratiche", text: "Ti affianchiamo nella gestione della documentazione tecnica e nelle pratiche necessarie, senza che tu debba pensarci.", image: commonImages.turnkey2 },
        { title: "Realizzazione", text: "Produciamo e installiamo direttamente, senza intermediari. Dalla nostra officina a casa tua, con un unico interlocutore.", image: commonImages.turnkey3 },
      ],
      closing: '"Un solo referente, dalla prima telefonata al cancello installato."',
    },
    products: {
      preLabel: "Cosa realizziamo",
      headlinePre: "Tutto ciò che puoi fare ",
      headlineAccent: "in ferro",
      subheadline: "Dalla progettazione alla posa in opera, realizziamo ogni lavoro internamente. Preventivo gratuito, consegna garantita.",
      viewAll: "Vedi tutte le lavorazioni",
      learnMore: "Scopri di più",
      items: [
        { name: "Cancelli e accessi", desc: "Accesso protetto e su misura per la tua proprietà. Cancelli scorrevoli, a battente, pedonali e automatizzati.", icon: "DoorOpen", link: "/cancelli" },
        { name: "Inferriate di sicurezza", desc: "Protezione per finestre e porte senza rinunciare all'estetica e alla luce naturale.", icon: "Grid3x3", link: "/inferriate" },
        { name: "Recinzioni", desc: "Perimetro sicuro e decorativo in ferro battuto o doghe modulari per ogni esigenza.", icon: "Fence", link: "/recinzioni" },
        { name: "Scale in ferro", desc: "Scale su misura per interni ed esterni, residenziali e industriali, resistenti nel tempo.", icon: "TrendingUp", link: "/lavorazioni#scale" },
        { name: "Carport e Tettoie", desc: "Strutture autoportanti in ferro su misura per proteggere auto e veicoli dagli agenti atmosferici.", icon: "CarFront", link: "/carport" },
        { name: "Automazione", desc: "Comfort e sicurezza con sistemi di automazione per cancelli e serramenti.", icon: "Settings", link: "/automazione" },
      ],
    },
    authority: {
      preLabel: "Perché scegliere Eurofabbro",
      headlinePre: "L'unica carpenteria ",
      headlineAccent: "certificata",
      headlinePost: " della zona",
      body: "Grazie alla certificazione dell'Istituto Giordano — ente tecnico fondato nel 1959 — i nostri cancelli sono testati per 60.000 aperture e marchiati CE. Siamo il punto di riferimento per carpenteria metallica certificata tra Bologna e Cento.",
      certBadge: "Certificati Istituto Giordano · Marcatura CE",
      stats: [
        { number: "49", label: "Anni di attività (1977–2026)" },
        { number: "60.000", label: "Aperture testate per marcatura CE" },
        { number: "100%", label: "Produzione interna su misura" },
        { number: "24h", label: "Per ricevere il tuo preventivo" },
      ],
    },
    process: {
      preLabel: "Il nostro processo",
      headlinePre: "Dalla ",
      headlineAccent: "richiesta",
      headlinePost: " alla posa in opera",
      steps: [
        { title: "1. Contattaci", desc: "Chiamaci, scrivici su WhatsApp o compila il form. Risponderemo entro 24 ore per fissare un sopralluogo gratuito.", icon: "MessageCircle" },
        { title: "2. Sopralluogo e progetto", desc: "Veniamo da te, misuriamo e progettiamo la soluzione su misura. Ti inviamo un preventivo dettagliato senza impegno.", icon: "Ruler" },
        { title: "3. Produzione e posa", desc: "Produciamo internamente e installiamo. Garantiamo il lavoro e siamo disponibili per ogni necessità post-installazione.", icon: "CircleCheckBig" },
      ],
    },
    featuredProjects: {
      preLabel: "I nostri lavori",
      headlinePre: "Ogni ",
      headlineAccent: "lavorazione",
      headlinePost: " racconta una storia",
      viewAll: "Vedi tutte le realizzazioni",
      projects: [
        { name: "Cancello Autoportante", location: "Bologna", image: commonImages.wp1, link: "/cancelli", span: 2 },
        { name: "Inferriate di Sicurezza", location: "Cento (FE)", image: commonImages.wp5, link: "/inferriate" },
        { name: "Scale e Strutture", location: "Crevalcore (BO)", image: commonImages.wpStrutture, link: "/lavorazioni" },
        { name: "Cancello a Battente", location: "San Giovanni in Persiceto (BO)", image: commonImages.wp2, link: "/cancelli" },
        { name: "Recinzioni su Misura", location: "Massa Finalese (MO)", image: commonImages.wpCancelli, link: "/recinzioni" },
        { name: "Grate Antieffrazione", location: "Bologna", image: commonImages.wpGrate, link: "/inferriate" },
      ],
    },
    deductionBanner: {
      headlinePre: "Risparmia fino al ",
      headlineAccent: "50%",
      headlinePost: " con le detrazioni fiscali",
      body: "Il Bonus Sicurezza ti permette di detrarre il 36% delle spese per cancelli, inferriate e sistemi di sicurezza. Con le detrazioni fiscali si arriva al 50%. Finanziamento a tasso agevolato con Compass, rate da 24 a 48 mesi.",
      cta: "Scopri come risparmiare",
      badges: ["Bonus Sicurezza 36%", "Detrazione 50%", "Compass 24/36/48 mesi"],
    },
    workWithUs: {
      preLabel: "Collabora con noi",
      headlinePre: "Cerchiamo ",
      headlineAccent: "partner",
      headlinePost: " e professionisti",
      subheadline: "Unisciti alla nostra rete. Siamo sempre alla ricerca di installatori, rivenditori e professionisti qualificati.",
      cta: "Scopri di più",
      ctaHref: "/landing/lavora-con-noi",
    },
    testimonials: {
      preLabel: "Dicono di noi",
      headlinePre: "La ",
      headlineAccent: "fiducia",
      headlinePost: " dei nostri clienti",
      items: [
        { quote: "Lavoro impeccabile sul nostro cancello scorrevole. Professionali, puntuali e il risultato ha superato le aspettative. Consigliatissimi.", name: "Marco R.", location: "Crevalcore (BO)", rating: 5 },
        { quote: "Abbiamo fatto realizzare le inferriate per tutta la casa. Qualità eccellente, installazione rapida e pulizia sul cantiere. Molto soddisfatti.", name: "Laura B.", location: "Cento (FE)", rating: 5 },
        { quote: "Ci siamo affidati a Ferioli per le recinzioni del capannone. Prezzo giusto, lavoro solido e duraturo. Li raccomandiamo senza riserve.", name: "Giovanni P.", location: "San Giovanni in Persiceto (BO)", rating: 5 },
      ],
    },
    faq: {
      title: "Domande Frequenti",
      items: [
        { q: "Lavorate in tutta la provincia di Bologna?", a: "Sì, operiamo nelle province di Bologna, Modena e Ferrara con sopralluoghi e installazioni dirette." },
        { q: "Quanto tempo richiede un cancello su misura?", a: "In media 3–6 settimane dalla conferma del preventivo, in base alla complessità del progetto." },
        { q: "Offrite finanziamenti?", a: "Sì, collaboriamo con Compass per piani rateali a tasso agevolato da 24 a 48 mesi." },
        { q: "I vostri prodotti sono marcati CE?", a: "Sì, siamo certificati Istituto Giordano — i nostri cancelli sono testati per 60.000 aperture e marchiati CE." },
        { q: "Gestite pratiche e permessi?", a: "Sì, il nostro servizio Valore Plus include la gestione di pratiche e permessi, così non devi preoccuparti." },
        { q: "Producete tutto internamente?", a: "Sì, progettiamo, produciamo e installiamo direttamente, senza intermediari." },
      ],
    },
    cta: {
      preLabel: "Inizia oggi",
      headlinePre: "Richiedi il tuo preventivo ",
      headlineAccent: "gratuito",
      subheadline: "Sopralluogo gratuito, preventivo senza impegno. Rispondiamo entro 24 ore.",
      btnForm: "Compila il form",
      btnWhatsapp: "Scrivici su WhatsApp",
      btnPhone: "051 985300",
      chip: "Contatti",
      primary: "Richiedi preventivo",
      whatsappPre: "Chat su",
      reassurance: ["Risposta entro 24 ore", "Sopralluogo gratuito", "Preventivo senza impegno"],
    },
    lavorazioni: {
      hero: {
        headlinePre: "Altre lavorazioni in ",
        headlineAccent: "ferro",
        subheadline: "Scale, balaustre, carport, dehor commerciali e arredi in ferro. Ogni progetto è studiato su misura per le tue esigenze.",
        cta: "Richiedi il tuo preventivo",
      },
      sections: [
        { id: "scale", name: "Scale in ferro", desc: "Progettiamo e realizziamo scale in ferro su misura per interni ed esterni, sia residenziali che industriali. Scale dritte, con pianerottolo, a struttura metallica — combinabili con legno, vetro o altri materiali.", image: commonImages.wpStrutture, href: "/scale" },
        { id: "balustre", name: "Balaustre e ringhiere", desc: "Realizziamo balaustre e ringhiere personalizzate per balconi, scale e terrazzi, nel rispetto delle normative di sicurezza. Parapetti e corrimano sia per interni che per esterni, con trattamento di zincatura per lunga durata.", image: commonImages.wpParapetti, href: "/balaustre" },
        { id: "carport", name: "Carport e tettoie", desc: "Realizziamo carport in ferro su misura: tettoie e pensiline autoportanti per proteggere auto e veicoli dagli agenti atmosferici. Personalizzabili e zincati per massima resistenza.", image: commonImages.carportSingle, href: "/carport" },
        { id: "dehor", name: "Dehor commerciali", desc: "Dehor su misura in ferro per bar, ristoranti e attività commerciali. Strutture resistenti, eleganti e personalizzabili a 360 gradi, nel rispetto delle normative comunali.", image: commonImages.wpDehor, href: "/dehor" },
        { id: "arredi", name: "Arredi in ferro", desc: "Produzione di arredi in ferro sia industriali che per la casa: scaffalature, banchi di lavoro, letti, mobili, arredo bagno, librerie. Tutto personalizzabile al 100% su misura.", image: commonImages.wpArredi, href: "/arredi" },
      ],
    },
    carport: {
      hero: {
        headlinePre: "Carport e tettoie in ",
        headlineAccent: "ferro su misura",
        subheadline: "Realizziamo carport e pensiline in ferro personalizzate per proteggere auto e veicoli dagli agenti atmosferici. Strutture autoportanti, zincate e verniciabili su richiesta.",
        cta: "Richiedi il tuo preventivo",
      },
      introTitlePre: "Protezione su misura per ", introTitleAccent: "la tua auto",
      introBody: "Un carport in ferro è la soluzione ideale per chi vuole proteggere il proprio veicolo dagli agenti atmosferici senza rinunciare all'estetica. Rispetto a un garage tradizionale, occupa meno spazio, costa meno e si integra perfettamente con il giardino o il vialetto d'accesso. Ogni struttura è progettata su misura, costruita nel nostro laboratorio e installata direttamente da noi.",
      featuresTitlePre: "Perché scegliere un carport in ", featuresTitleAccent: "ferro", featuresTitlePost: "",
      features: ["Struttura autoportante senza pilastri intermedi", "Zincatura a caldo per massima resistenza alle intemperie", "Personalizzabile in dimensioni, forme e finiture", "Adatto a uso residenziale e industriale", "Compatibile con pannelli fotovoltaici", "Manutenzione minima nel tempo", "Produzione interna e installazione diretta", "Preventivo gratuito entro 24h"],
      typesTitlePre: "Tipologie di ", typesTitleAccent: "coperture",
      types: [
        { name: "Carport singolo", desc: "Copertura per un singolo veicolo, ideale per abitazioni private con accesso carrabile. Design pulito e integrato con l'architettura esistente. Disponibile in varie larghezze e altezze.", image: commonImages.carportSingle },
        { name: "Carport doppio", desc: "Soluzione per due o più veicoli, perfetta per famiglie o piccole attività. Struttura robusta con ampio spazio utile. Possibilità di aggiungere pareti laterali o pannelli di chiusura.", image: commonImages.carportDouble },
        { name: "Pensiline industriali", desc: "Coperture su misura per aziende, magazzini e aree di carico/scarico. Alta resistenza e lunga durata garantita. Ideali per grandi superfici con alta portata strutturale.", image: commonImages.carportIndustrial },
        { name: "Tettoie per esterni", desc: "Protezione per ingressi, terrazzi e aree esterne. Eleganti, personalizzabili e resistenti alle intemperie. Perfette anche per proteggere aree di sosta camper o moto.", image: commonImages.carportOutdoor },
      ],
      materialsTitlePre: "Materiali e ", materialsTitleAccent: "finiture",
      materials: [
        { name: "Ferro zincato a caldo", desc: "La zincatura a caldo garantisce la massima protezione dalla ruggine e dagli agenti atmosferici, con una durata superiore a 20 anni senza manutenzione." },
        { name: "Verniciatura a polvere", desc: "Disponibile in qualsiasi colore RAL. La verniciatura a polvere offre un'ottima resistenza agli urti e ai raggi UV, mantenendo il colore invariato nel tempo." },
        { name: "Coperture in policarbonato", desc: "Pannelli trasparenti o traslucidi che lasciano passare la luce naturale pur proteggendo dalla pioggia. Leggeri, resistenti e isolanti." },
        { name: "Lamiera grecata", desc: "Soluzione economica e robusta per coperture opache. Alta resistenza meccanica e impermeabilità garantita nel tempo." },
      ],
      faq: [
        { q: "Quanto costa un carport in ferro su misura?", a: "Il costo varia in base alle dimensioni, alla tipologia di copertura e alle finiture scelte. Dopo un sopralluogo gratuito ti forniamo un preventivo dettagliato e senza impegno." },
        { q: "È necessario il permesso edilizio per installare un carport?", a: "Dipende dalle dimensioni e dal comune di riferimento. Per strutture di piccole dimensioni spesso è sufficiente la CILA. Vi assistiamo nell'iter burocratico." },
        { q: "In quanto tempo viene realizzato e installato?", a: "I tempi dipendono dalla complessità del progetto. Mediamente, dalla conferma del preventivo all'installazione passano 3-6 settimane." },
        { q: "I carport sono compatibili con pannelli solari?", a: "Sì, progettiamo le strutture per accogliere pannelli fotovoltaici, ottimizzando il dimensionamento dei profilati per la portata aggiuntiva." },
        { q: "Operate in tutta la provincia di Bologna?", a: "Operiamo nelle province di Bologna e Modena con sopralluoghi e installazioni dirette." },
      ],
    },
    realizzazioni: {
      hero: {
        headlinePre: "Le nostre ",
        headlineAccent: "realizzazioni",
        subheadline: "Ogni progetto racconta una storia di qualità artigianale, attenzione al dettaglio e soddisfazione del cliente.",
        cta: "Richiedi il tuo preventivo",
      },
      projects: [
        { name: "Cancello Scorrevole", location: "Bologna", type: "Cancello", image: commonImages.wpCarpenteria, link: "/cancelli" },
        { name: "Cancello a Battente", location: "Cento (FE)", type: "Cancello", image: commonImages.wp2, link: "/cancelli" },
        { name: "Recinzioni", location: "Massa Finalese (MO)", type: "Recinzione", image: commonImages.wpCancelli, link: "/recinzioni" },
        { name: "Scala Interna", location: "Bologna", type: "Struttura", image: commonImages.wp4, link: "/lavorazioni" },
        { name: "Grate Antieffrazione", location: "Crevalcore (BO)", type: "Inferriata", image: commonImages.wpGrate, link: "/inferriate" },
        { name: "Scala Esterna", location: "San Giovanni in Persiceto (BO)", type: "Struttura", image: commonImages.wpStrutture, link: "/lavorazioni" },
        { name: "Balaustra e Parapetto", location: "Bologna", type: "Ringhiera", image: commonImages.wpParapetti, link: "/lavorazioni" },
        { name: "Arredi su Misura", location: "Cento (FE)", type: "Arredo", image: commonImages.wpArredi, link: "/lavorazioni" },
        { name: "Dehor Commerciale", location: "Bologna", type: "Struttura", image: commonImages.wpDehor, link: "/lavorazioni" },
        { name: "Cancello in Lamiera", location: "Crevalcore (BO)", type: "Cancello", image: commonImages.wp3, link: "/cancelli" },
      ],
    },
    detrazioni: {
      hero: {
        headlinePre: "Risparmia fino al ",
        headlineAccent: "50%",
        headlinePost: " grazie alle detrazioni fiscali",
        subheadline: "Detrazioni fiscali 2026 per cancelli, inferriate e sistemi di sicurezza. Il momento giusto per intervenire.",
        cta: "Richiedi informazioni",
      },
      bonusTitlePre: "Bonus Sicurezza e ", bonusTitleAccent: "Bonus Ristrutturazioni", bonusTitlePost: "",
      bonusBody: "Nel 2026 sono ancora previste agevolazioni fiscali per interventi che migliorano la sicurezza degli immobili. Gli interventi su cancelli, grate di sicurezza, recinzioni e sistemi di controllo accessi possono rientrare nelle detrazioni fiscali per la sicurezza e la ristrutturazione edilizia.",
      eligibleTitlePre: "Quali interventi possono essere ", eligibleTitleAccent: "detraibili", eligibleTitlePost: "",
      eligible: ["Installazione di inferriate di sicurezza", "Installazione o rifacimento di cancelli", "Automazione dei cancelli", "Recinzioni e sistemi di controllo accessi", "Sistemi antifurto e videosorveglianza"],
      compassTitlePre: "Finanziamenti e soluzioni di ", compassTitleAccent: "pagamento", compassTitlePost: "",
      compassBody: "Per facilitare l'intervento, offriamo la possibilità di accedere a finanziamenti con piani rateali personalizzati da 24, 36 o 48 mesi, così da installare subito senza rinunciare alla qualità.",
      calcTitlePre: "Calcola il tuo ", calcTitleAccent: "risparmio", calcTitlePost: "",
      calcLabel: "Valore indicativo del progetto (€)",
      calcPlaceholder: "es. 5000",
      calcResult36: "Con il Bonus Sicurezza (36%)",
      calcResult50: "Con le detrazioni (50%)",
      calcSave: "Risparmi",
      faq: [
        { q: "Quali prodotti rientrano nelle detrazioni?", a: "Cancelli, inferriate, sistemi di allarme, videosorveglianza e tutti gli interventi che migliorano la sicurezza dell'immobile." },
        { q: "Come si ottiene la detrazione?", a: "È necessario effettuare il pagamento tramite bonifico parlante e conservare la documentazione. I nostri consulenti possono guidarvi." },
        { q: "È possibile finanziare il lavoro?", a: "Sì, offriamo piani rateali con Compass da 24 a 48 mesi per rendere l'investimento accessibile." },
        { q: "Le inferriate sono sempre detraibili?", a: "Sì, l'installazione delle inferriate rientra negli interventi di sicurezza ed è fiscalmente detraibile sia per nuove installazioni che per sostituzioni." },
      ],
    },
    contatti: {
      headlinePre: "Siamo a ",
      headlineAccent: "due passi",
      detailsTitle: "I nostri recapiti",
      requestTitle: "Invia una richiesta",
      contactLabels: {
        phone: "Telefono",
        whatsapp: "WhatsApp",
        email: "Email",
        address: "Indirizzo",
        hours: "Orari",
      },
      processTitle: "Cosa succede dopo che ci contatti",
      processSteps: ["Risponderemo entro 24h", "Sopralluogo gratuito", "Preventivo senza impegno"],
      form: {
        name: "Nome e cognome *",
        phone: "Telefono *",
        email: "Email",
        type: "Tipo di lavoro",
        typeOptions: ["-- Seleziona --", "Cancello", "Inferriata", "Recinzione", "Scala", "Allarme", "Automazione", "Altro"],
        message: "Messaggio",
        privacy: "Accetto la privacy policy e il trattamento dei dati personali *",
        submit: "Invia richiesta",
        success: "Richiesta inviata con successo! Ti contatteremo entro 24 ore.",
        error: "Si è verificato un errore. Riprova o contattaci telefonicamente.",
      },
    },
    footer: {
      tagline: "Carpenteria metallica certificata dal 1977.",
      colLavorazioni: "Lavorazioni",
      colContatti: "Contatti",
      colCertificazioni: "Certificazioni",
      certText: "Certificati Istituto Giordano · Marcatura CE",
      compassText: "Finanziamenti Compass disponibili",
      copyright: "© 2024 Ferioli Sergio SRL",
      privacy: "Privacy Policy",
      cookie: "Preferenze cookie",
      piva: "P.IVA 02128491202",
    },
    form: {
      name: "Nome completo",
      email: "Email",
      phone: "Telefono",
      message: "Come possiamo aiutarti?",
      privacy: "Inviando accetti la",
      privacyLink: "privacy policy",
      send: "Invia richiesta",
      sent: "Richiesta inviata",
      success: "Grazie! Ti ricontatteremo entro 24 ore.",
      error: "Qualcosa è andato storto. Chiamaci direttamente.",
    },
    common: {
      learnMore: "Scopri di più",
      readMore: "Leggi di più",
      requestQuote: "Richiedi il tuo preventivo",
      viewAll: "Vedi tutti",
      callUs: "Chiama {phone}",
      whatsappLabel: "WhatsApp: {display}",
    },
    pageLabels: {
      tipologie: "Tipologie",
      benefici: "Benefici",
      material: "Materiale",
      modular: "Modulare",
      intro: "Introduzione",
      why: "Perché",
      catalog: "Catalogo",
      materials: "Materiali",
      bonus: "Bonus",
      eligible: "Agevolabili",
      financing: "Finanziamento",
      process: "Processo",
      reach: "Contattaci",
      write: "Scrivici",
      heritage: "Storia",
      howItWorks: "Come funziona",
      types: "Tipologie",
      controls: "Comandi",
      service: "Servizio",
      apply: "Candidati",
      getInTouch: "Mettiti in contatto",
      project: "Raccontaci il tuo progetto",
      quote24: "Rispondiamo entro 24 ore con un preventivo senza impegno.",
      ctaTitle: "Richiedi il tuo preventivo gratuito",
      partners: "Installatori, rivenditori, architetti, imprese edili.",
      gutters: ["Cancelli & Recinzioni · Bologna", "Lavora con noi · Bologna, Italia"],
    },
    cancelli: {
      hero: {
        headlinePre: "Cancelli in ferro ",
        headlineAccent: "su misura",
        subheadline: "Cancelli scorrevoli, a battente, pedonali e autoportanti. Progettati, costruiti e installati internamente. Certificati Istituto Giordano, marcati CE.",
        cta: "Richiedi preventivo gratuito",
      },
      variantsTitlePre: "Ogni tipologia, ",
      variantsTitleAccent: "ogni apertura",
      variantsTitlePost: "",
      variants: [
        { name: "Cancelli scorrevoli", desc: "Ideali per passaggi stretti e spazi limitati. Silenziosi, affidabili, testati per oltre 60.000 aperture.", href: "/cancelli/scorrevole" },
        { name: "Cancelli a battente", desc: "Una o due ante, classici o di design. Manuali o automatizzati, zincati a caldo a richiesta.", href: "/cancelli/battente" },
        { name: "Cancelli pedonali", desc: "Coordinati al cancello principale per stile, materiale e finitura. Perfetti per l'accesso quotidiano.", href: "/cancelli/pedonali" },
        { name: "Cancelli autoportanti", desc: "Senza guida a terra: ideali per passaggi sconnessi, neve e ghiaia. Puliti, silenziosi, robusti.", href: "/cancelli/autoportanti" },
      ],
      galleryEyebrow: "Tipologie in officina",
      galleryTitlePre: "Ogni ",
      galleryTitleAccent: "apertura",
      galleryTitlePost: ", una soluzione",
      galleryItems: [
        { label: "Scorrevoli" },
        { label: "Battente" },
        { label: "Pedonali" },
        { label: "Autoportanti" },
      ],
      certStripTitle: "Certificati Istituto Giordano",
      certStripSub: "Marcatura CE · Testato per 60.000 aperture",
      whyTitlePre: "Perché un cancello ",
      whyTitleAccent: "Ferioli Sergio",
      whyBenefits: [
        "Certificati Istituto Giordano — primi in Italia per cancelli manuali e automatici",
        "60.000 aperture testate su ogni modello certificato",
        "Zincatura a caldo e verniciatura a polvere a richiesta",
        "Produzione 100% interna, installazione diretta dal nostro team",
        "Marcatura CE e documentazione tecnica completa",
        "Detraibile con Bonus Sicurezza 50%",
      ],
      prontaTitlePre: "Un cancello ",
      prontaTitleAccent: "pronto da installare",
      prontaBody: "Consegniamo cancelli finiti e certificati, installati dal nostro team. Nessun intermediario, nessuna sorpresa, nessuna soluzione standard.",
      faq: [
        { q: "Quanto tempo serve per realizzare un cancello su misura?", a: "In media 4-6 settimane dal sopralluogo, in funzione del design, delle dimensioni e delle finiture. Nel preventivo confermiamo una tempistica precisa." },
        { q: "Automatizzate anche cancelli già esistenti?", a: "Sì. Interveniamo su cancelli manuali esistenti (nostri o di terzi) con motori, elettronica di controllo e dispositivi di sicurezza a norma CE." },
        { q: "Che garanzia offrite sui vostri cancelli?", a: "Ogni cancello Ferioli Sergio è coperto da 10 anni di garanzia strutturale sul telaio e 24 mesi su motori ed elettronica." },
        { q: "Vi occupate delle pratiche per le detrazioni fiscali?", a: "Sì. Forniamo documentazione tecnica, dichiarazione di conformità e fattura con i dati corretti per accedere al Bonus Sicurezza 50%." },
      ],
    },
    inferriate: {
      hero: {
        headlinePre: "Inferriate di ",
        headlineAccent: "sicurezza",
        subheadline: "Inferriate fisse, apribili, snodabili e a due ante. Produzione interna, marcatura CE, su misura per le tue finestre e porte.",
        cta: "Richiedi preventivo gratuito",
      },
      variantsTitlePre: "Ogni tipologia",
      variantsTitleAccent: " per ogni apertura",
      variantsTitlePost: "",
      variants: [
        { name: "Inferriate fisse", desc: "Robuste e senza manutenzione. Ideali per finestre e aperture al piano terra che non necessitano di apertura.", href: "/inferriate/fisse" },
        { name: "Inferriate apribili", desc: "Una o due ante, apertura laterale o a libro. Sicure e pratiche, con serratura a chiave.", href: "/inferriate/apribili" },
        { name: "Inferriate snodabili", desc: "Apertura a libro, ideali per porte-finestre e vetrine. Compatte, eleganti, sicure.", href: "/inferriate/snodabili" },
        { name: "Inferriate a due ante", desc: "Per aperture ampie: classica cerniera a due ante, con serratura unica centrale. Massima sicurezza, look classico.", href: "/inferriate/due-ante" },
      ],
      galleryEyebrow: "Tipologie in officina",
      galleryTitlePre: "Sicurezza ",
      galleryTitleAccent: "per ogni apertura",
      galleryItems: [
        { label: "Fisse" },
        { label: "Apribili" },
        { label: "Snodabili" },
        { label: "Due ante" },
      ],
      benefitsTitlePre: "Sicurezza che si ",
      benefitsTitleAccent: "integra",
      benefitsTitlePost: " con la tua casa",
      benefits: [
        "Progettate su misura per le tue finestre e porte",
        "Zincate e verniciate a richiesta, ampia gamma colori",
        "Sblocco interno e serrature a prova di bambino",
        "Compatibili con antifurto e domotica",
        "Marcatura CE e certificazione classe di resistenza EN 1627",
        "Detraibili con Bonus Sicurezza 50%",
      ],
      faq: [
        { q: "Le inferriate sono sicure in caso di emergenza?", a: "Sì. Ogni inferriata apribile ha un meccanismo di sblocco rapido dall'interno, senza chiave. Esci in pochi secondi." },
        { q: "Richiedono manutenzione?", a: "Le inferriate zincate a caldo e verniciate a polvere sono senza manutenzione. Consigliamo un controllo visivo annuale su cerniere e serrature." },
        { q: "Posso abbinare il colore delle inferriate alle persiane?", a: "Certamente. Offriamo un'ampia gamma di colori RAL e finiture per coordinare le inferriate ai tuoi infissi esistenti." },
        { q: "Installate inferriate anche su porte-finestre?", a: "Sì. Le inferriate snodabili sono pensate per le aperture ampie. Realizziamo anche soluzioni su misura per portoncini d'ingresso e finestre ad arco." },
      ],
    },
    recinzioni: {
      hero: {
        headlinePre: "Recinzioni ",
        headlineAccent: "su misura",
        subheadline: "Doghe modulari, reti metalliche, decorative e di sicurezza. Progettazione interna, zincatura a caldo a richiesta, marcatura CE.",
        cta: "Richiedi preventivo gratuito",
      },
      ironTitlePre: "Ferro, reti e ",
      ironTitleAccent: "doghe modulari",
      ironBody: "Dalle recinzioni in ferro decorativo per ville ai sistemi a doghe modulari per capannoni: progettiamo e realizziamo la recinzione giusta per ogni esigenza, con zincatura a caldo e verniciatura a polvere a richiesta.",
      benefits: [
        "Zincate a caldo e verniciate a polvere",
        "Doghe modulari, reti e ferro decorativo",
        "Progetto su misura, produzione interna",
        "Pali, cancelli e accessori nella stessa finitura",
      ],
      galleryEyebrow: "Tipologie in officina",
      galleryTitlePre: "Doghe, reti",
      galleryTitleAccent: " e moduli su misura",
      galleryItems: [
        { label: "Ferro modulare" },
        { label: "Reti metalliche" },
        { label: "Rete decorativa" },
        { label: "Decorativa" },
      ],
      faq: [
        { q: "Quale recinzione è ideale per un'abitazione privata?", a: "Per le residenze consigliamo recinzioni in ferro decorativo o sistemi a doghe modulari. Valutiamo stile, altezza e destinazione d'uso in fase di sopralluogo." },
        { q: "Installate anche cancelli coordinati alla recinzione?", a: "Sì. Realizziamo cancelli pedonali e carrabili nello stesso materiale e finitura della recinzione, per un risultato coerente." },
        { q: "Quanto tempo richiede l'installazione?", a: "Per una recinzione standard di 30 metri lineari, l'installazione richiede 2-4 giorni, più 4-6 settimane per la produzione su misura." },
        { q: "Vi occupate anche delle fondamenta?", a: "Sì. Il nostro team realizza i plinti di fondazione per i pali, le basi e ogni lavorazione edile necessaria, per una consegna chiavi in mano." },
      ],
    },
    automazione: {
      hero: {
        headlinePre: "Sistemi di ",
        headlineAccent: "automazione",
        headlinePost: " per cancelli",
        subheadline: "Realizziamo e installiamo sistemi di automazione per cancelli, porte e serramenti. Controllo tramite telecomando, smartphone e sistemi domotici.",
        cta: "Richiedi consulenza",
      },
      howTitlePre: "Come ",
      howTitleAccent: "lavoriamo",
      howTitlePost: " sull'automazione",
      howBody: "Ogni progetto di automazione inizia con un sopralluogo. Valutiamo spazio, peso, frequenza d'uso e sistema di controllo preferito. Proponiamo motore, accessori e dispositivi di sicurezza per la piena conformità EN 12453.",
      typesTitlePre: "Tipologie",
      typesTitleAccent: " di automazione",
      typesTitlePost: "",
      typesBody: "Automazione per cancelli scorrevoli, a battente, pedonali e autoportanti. Progettazione interna, motori di marca, marcatura CE, assistenza post-installazione.",
      types: [
        { name: "Motori per scorrevoli", desc: "Funzionamento silenzioso, soft start e stop, ciclo di lavoro 100%, testati per oltre 60.000 aperture." },
        { name: "Motori interrati", desc: "Motorizzazione nascosta per un'estetica pulita. Progettati per cancelli a battente fino a 4m e 800kg per anta." },
        { name: "Bracci articolati", desc: "Per cancelli a battente con pilastri larghi. Robusti, affidabili, ideali per uso residenziale e industriale." },
      ],
      controlsTitle: "Come controllare il cancello",
      controls: [
        "Telecomando",
        "Tastierino e citofono",
        "App per smartphone",
        "Sensori e sicurezza",
      ],
      serviceTitlePre: "Un unico ",
      serviceTitleAccent: "referente",
      serviceTitlePost: " per la tua automazione",
      serviceBody: "Dalla progettazione all'installazione, dalla garanzia alla manutenzione programmata: siamo il tuo unico partner per l'automazione di cancelli e serramenti. Marcati CE, certificati, assistiti.",
    },
    percheNoi: {
      hero: {
        headlinePre: "Quarantanove anni ",
        headlineAccent: "di ferro",
        headlinePost: " — fatto a mano",
        subheadline: "Tre generazioni della famiglia Ferioli Sergio lavorano il ferro nella nostra officina vicino Bologna dal 1977. Ogni cancello, inferriata e recinzione nasce qui.",
        cta: "Scopri la nostra officina",
      },
      storyTitlePre: "La nostra storia, la nostra ",
      storyTitleAccent: "officina",
      storyTitlePost: "",
      storyBody: "Fondata nel 1977 a Palata Pepoli di Crevalcore, la nostra officina è cresciuta da una bottega artigiana a un team di 12 artigiani specializzati. Lavoriamo il ferro come si è sempre fatto: a mano, con strumenti moderni ma la stessa cura.",
      guaranteeTitlePre: "Lavoro certificato, ",
      guaranteeTitleAccent: "garantito",
      guaranteeTitlePost: " nel tempo",
      guaranteeBody: "Ogni prodotto Ferioli Sergio porta il nostro nome ed è coperto da 10 anni di garanzia strutturale. Siamo sul campo per installazione, manutenzione programmata e assistenza post-installazione.",
      highlights: [
        "49 anni di esperienza artigianale",
        "Primi in Italia certificati CE (Istituto Giordano)",
        "Produzione interna, installazione diretta",
      ],
      workshopCards: [
        { label: "Officina", alt: "Officina Ferioli Sergio — banchi di lavoro" },
        { label: "Magazzino", alt: "Scaffalature industriali e magazzino" },
        { label: "Produzione", alt: "Prodotti in ferro su misura in produzione" },
      ],
    },
    landings: {
      cancelliRecinzioni: {
        heroEyebrow: "Cancelli e Recinzioni · Bologna",
        heroTitlePre: "Cancelli e recinzioni ",
        heroTitleAccent: "in ferro su misura",
        heroSub: "Produzione e installazione di cancelli e recinzioni in ferro su misura. 49 anni di esperienza, marcatura CE, sopralluogo gratuito a Bologna e Modena.",
        heroCta: "Richiedi preventivo",
        benefitsTitle: "Perché sceglierci",
        benefits: [
          "Sopralluogo gratuito entro 24h",
          "Progetto su misura, produzione interna",
          "Zincatura a caldo e verniciatura a richiesta",
          "Marcatura CE e documentazione tecnica completa",
          "Installazione diretta dal nostro team",
          "Detraibile con Bonus Sicurezza 50%",
        ],
        certTitle: "Certificati primi in Italia",
        certBody: "Certificazione Istituto Giordano, marcatura CE su ogni installazione.",
        requestEyebrow: "Richiesta",
      },
      lavoraConNoi: {
        heroEyebrow: "Lavora con noi · Bologna",
        heroTitlePre: "Collabora con ",
        heroTitleAccent: "Ferioli Sergio",
        heroSub: "Cerchiamo installatori, rivenditori, architetti e professionisti qualificati. Unisciti alla nostra rete di partner.",
        heroCta: "Invia la tua candidatura",
        benefitsTitle: "Con chi lavoriamo",
        benefits: [
          "Installatori e posatori",
          "Rivenditori e showroom",
          "Architetti e ingegneri",
          "Imprese edili",
        ],
        certTitle: "49 anni di esperienza qualificata",
        certBody: "Certificati Istituto Giordano, marcatura CE, produzione interna. Una qualità su cui costruire un business.",
        requestEyebrow: "Candidati",
      },
    },
    wppage: {
      fallbackTitle: "Pagina non disponibile",
      fallbackBody: "Contenuto non trovato per: {slug}",
      galleryEyebrow: "Realizzazioni",
      galleryTitlePre: "Altre ",
      galleryTitleAccent: "lavorazioni su misura",
      relatedTitle: "Approfondimenti",
    },
    notFound: {
      title: "Pagina non trovata",
      body: "La pagina che stai cercando non esiste o è stata spostata. Torna in carreggiata da qui.",
      ctaHome: "Torna alla home",
    },
    grazie: {
      eyebrow: "Messaggio ricevuto",
      titlePre: "Grazie per averci",
      titleAccent: "contattato",
      body: "Abbiamo ricevuto la tua richiesta. Il nostro staff ti ricontatterà al più presto.",
      ctaHome: "Torna alla home",
    },
  },
};

export type Lang = keyof typeof translations;
export type T = (typeof translations)[Lang];
