// Eurofabbro content - bilingual (IT/EN)
// All content extracted from the original base44 SPA bundle

export const site = {
  name: "Eurofabbro",
  company: "Ferioli Sergio SRL",
  phone: "051 985300",
  phoneTel: "+39051985300",
  mobile: "347 4287776",
  mobileTel: "+393474287776",
  whatsapp: "393474287776",
  whatsappDisplay: "347 4287776",
  email: "eurofabbro@eurofabbro.com",
  address: "Via Galileo Galilei 140, 40014 Palata Pepoli di Crevalcore (BO)",
  hours: "Mon–Fri 8:00–18:00 · Sat by appointment",
  founded: 1977,
  logo: "/images/logo-landing.png",
  logoLanding: "/images/logo-landing.png",
  social: {
    facebook: "https://www.facebook.com/EUROFABBRO/",
    instagram: "https://www.instagram.com/eurofabbro/",
  },
} as const;

// Top-level navigation items shared between languages
const navBase = [
  { key: "servizi", href: "/lavorazioni" },
  { key: "percheNoi", href: "/perche-noi" },
  { key: "realizzazioni", href: "/realizzazioni" },
  { key: "detrazioni", href: "/detrazioni" },
  { key: "contatti", href: "/contatti" },
] as const;

// Sub-items shown under the "Servizi / Services" menu
const servicesBase = [
  { key: "lavorazioni", href: "/lavorazioni", descKey: "lavorazioniDesc" },
  { key: "cancelli", href: "/cancelli", descKey: "cancelliDesc" },
  { key: "inferriate", href: "/inferriate", descKey: "inferriateDesc" },
  { key: "recinzioni", href: "/recinzioni", descKey: "recinzioniDesc" },
  { key: "carport", href: "/carport", descKey: "carportDesc" },
  { key: "automazione", href: "/automazione", descKey: "automazioneDesc" },
] as const;

export const translations = {
  en: {
    lang: "en" as const,
    nav: {
      items: navBase,
      services: servicesBase,
      label: {
        servizi: "Services",
        lavorazioni: "Products",
        cancelli: "Gates",
        inferriate: "Security Bars",
        recinzioni: "Fencing",
        altreLavorazioni: "Other Works",
        carport: "Carports & Canopies",
        automazione: "Automation",
        percheNoi: "Why Us",
        realizzazioni: "Portfolio",
        detrazioni: "Tax Deductions",
        contatti: "Contact",
        cta: "Request a Quote",
        lavorazioniDesc: "Stairs, balustrades, furniture and more",
        cancelliDesc: "Sliding, swing, pedestrian and automated",
        inferriateDesc: "Custom security bars for every opening",
        recinzioniDesc: "Wrought iron and modular fencing",
        carportDesc: "Custom canopies for vehicles and outdoors",
        automazioneDesc: "Smart motors for every gate type",
        viewAllServices: "View all services",
      },
    },
    hero: {
      badge: "Istituto Giordano Certified · CE",
      headlineLine1: "Custom metalwork",
      headlineLine2Pre: "",
      headlineLine2Accent: "certified",
      headlineLine2Post: " craftsmanship",
      subheadline:
        "Forty years of ironwork in the Bologna province. In-house production, CE marking, guaranteed quality on every installation.",
      ctaPrimary: "Request a free quote",
      ctaSecondary: "Explore our work",
      stat1: "1977–2026 | 49 Years of experience",
      stat2: "Istituto Giordano Certified",
      stat3: "Free quote within 24h",
    },
    products: {
      preLabel: "What we make",
      headlinePre: "Everything you can craft in ",
      headlineAccent: "iron",
      subheadline:
        "From design to installation, every project is produced in-house. Free quotes, guaranteed delivery.",
      viewAll: "View all products",
      learnMore: "Learn more",
      items: [
        { name: "Gates & Access", desc: "Custom-made protected access for your property. Sliding, swing, pedestrian and automated gates.", icon: "DoorOpen", link: "/cancelli" },
        { name: "Security Bars", desc: "Window and door protection without sacrificing aesthetics or natural light.", icon: "Grid3x3", link: "/inferriate" },
        { name: "Fencing", desc: "Secure and decorative perimeter in wrought iron or modular slats for every need.", icon: "Fence", link: "/recinzioni" },
        { name: "Iron Stairs", desc: "Custom stairs for indoor and outdoor, residential and industrial, built to last.", icon: "TrendingUp", link: "/lavorazioni#scale" },
        { name: "Carports & Canopies", desc: "Custom self-supporting iron structures to protect vehicles from the elements.", icon: "Car", link: "/carport" },
        { name: "Automation", desc: "Comfort and security with gate and shutter automation systems.", icon: "Settings", link: "/automazione" },
      ],
    },
    turnkey: {
      preLabel: "Valore Plus by Ferioli",
      headlinePre: "Valore Plus — Ferioli's ",
      headlineAccent: "turnkey service",
      headlinePost: "",
      subheadline: "From design to installation: we take care of everything.",
      cards: [
        { title: "Design", text: "Site visit, measurements and custom design. We study every detail based on your space, style and current regulations.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/2a8eed53a_generated_image.png" },
        { title: "Paperwork", text: "We assist you in managing technical documentation and necessary paperwork, so you don't have to worry about it.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/81e9c3696_generated_image.png" },
        { title: "Production", text: "We produce and install directly, without intermediaries. From our workshop to your home, with a single point of contact.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/a18bfad4e_generated_image.png" },
      ],
      closing: '"A single point of contact, from the first call to the installed gate."',
    },
    authority: {
      preLabel: "Why choose Eurofabbro",
      headlinePre: "The only ",
      headlineAccent: "certified",
      headlinePost: " metalworks in the area",
      body: "Thanks to Istituto Giordano certification — a technical body founded in 1959 — our gates are tested for 60,000 openings and CE marked. We are the trusted reference for certified metalwork between Bologna and Cento.",
      certBadge: "Istituto Giordano Certified · CE Marking",
      stats: [
        { number: "49", label: "Years in business (1977-2026)" },
        { number: "60,000", label: "Openings tested for CE marking" },
        { number: "100%", label: "In-house custom production" },
        { number: "24h", label: "To receive your quote" },
      ],
    },
    process: {
      preLabel: "Our process",
      headlinePre: "From ",
      headlineAccent: "request",
      headlinePost: " to installation",
      steps: [
        { title: "1. Contact us", desc: "Call, WhatsApp or fill the form. We'll respond within 24 hours to schedule a free site visit.", icon: "MessageCircle" },
        { title: "2. Survey & design", desc: "We visit, measure and design the bespoke solution. You receive a detailed, no-obligation quote.", icon: "Ruler" },
        { title: "3. Production & install", desc: "We produce in-house and install. We guarantee the work and remain available for any post-installation need.", icon: "CheckCircle" },
      ],
    },
    featuredProjects: {
      preLabel: "Our work",
      headlinePre: "Every ",
      headlineAccent: "project",
      headlinePost: " tells a story",
      viewAll: "View all projects",
      projects: [
        { name: "Self-supporting Gate", location: "Bologna", image: "https://eurofabbro.com/wp-content/uploads/slider2/1.jpeg", link: "/cancelli" },
        { name: "Security Bars", location: "Cento (FE)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/5.jpg", link: "/inferriate" },
        { name: "Stairs & Structures", location: "Crevalcore (BO)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg", link: "/lavorazioni" },
        { name: "Swing Gate", location: "San Giovanni in Persiceto (BO)", image: "https://eurofabbro.com/wp-content/uploads/slider2/2.jpeg", link: "/cancelli" },
        { name: "Custom Fencing", location: "Massa Finalese (MO)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Cancelli-in-ferro-cento-1-300x225.jpg", link: "/recinzioni" },
        { name: "Anti-burglar Grilles", location: "Bologna", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-grate-in-ferro-bologna-480x360-1.jpg", link: "/inferriate" },
      ],
    },
    deductionBanner: {
      headlinePre: "Save up to ",
      headlineAccent: "50%",
      headlinePost: " with tax deductions",
      body: "The Security Bonus allows you to deduct 36% of expenses for gates, security bars and alarm systems. With tax deductions it reaches 50%. Subsidised financing with Compass, 24 to 48 month plans.",
      cta: "Discover how to save",
      badges: ["Security Bonus 36%", "Tax Deductions 50%", "Compass 24/36/48 months"],
    },
    testimonials: {
      preLabel: "What clients say",
      headlinePre: "The ",
      headlineAccent: "trust",
      headlinePost: " of our clients",
      items: [
        { quote: "Impeccable work on our sliding gate. Professional, punctual, and the result exceeded expectations. Highly recommended.", name: "Marco R.", location: "Crevalcore (BO)", rating: 5 },
        { quote: "We had security bars fitted throughout the house. Excellent quality, quick installation and clean worksite. Very satisfied.", name: "Laura B.", location: "Cento (FE)", rating: 5 },
        { quote: "We relied on Ferioli for our warehouse fencing. Fair price, solid and lasting work. We recommend them without reservation.", name: "Giovanni P.", location: "San Giovanni in Persiceto (BO)", rating: 5 },
      ],
    },
    cta: {
      preLabel: "Start today",
      headlinePre: "Request your free ",
      headlineAccent: "quote",
      subheadline: "Free site visit, no-obligation quote. We respond within 24 hours.",
      btnForm: "Fill the form",
      btnWhatsapp: "WhatsApp us",
      btnPhone: "051 985300",
      reassurance: ["Response within 24 hours", "Free site visit", "No-obligation quote"],
    },
    workWithUs: {
      preLabel: "Work with us",
      headlinePre: "Looking for ",
      headlineAccent: "partners",
      headlinePost: " and professionals",
      subheadline: "Join our network. We are always looking for installers, resellers, and qualified professionals.",
      cta: "Learn more",
    },
    footer: {
      tagline: "Certified metalwork since 1984.",
      colLavorazioni: "Products",
      colContatti: "Contact",
      colCertificazioni: "Certifications",
      certText: "Istituto Giordano Certified · CE Marking",
      compassText: "Compass financing available",
      copyright: "© 2024 Ferioli Sergio SRL",
      privacy: "Privacy Policy",
      cookie: "Cookie preferences",
      piva: "VAT IT02128491202",
    },
    form: {
      name: "Full name",
      email: "Email",
      phone: "Phone",
      message: "How can we help?",
      privacy: "By submitting you accept the",
      privacyLink: "privacy policy",
      send: "Send request",
      sent: "Request sent",
      success: "Thanks! We'll get back to you within 24 hours.",
      error: "Something went wrong. Please call us directly.",
    },
    cancelli: {
      hero: {
        headline: "Custom gates and ",
        headlineAccent: "ready delivery",
        subheadline: "We produce and sell gates of any type. Custom solutions based on client needs, guaranteed quality and superior aesthetics.",
        cta: "Request your quote",
      },
      variantsTitle: "Every ",
      variantsTitleAccent: "type",
      variantsTitlePost: " made to measure",
      variants: [
        { name: "Sliding gates", desc: "Traditional ground-guided, suspended and self-supporting sliding gates. Galvanised and paintable on request." },
        { name: "Pedestrian gates", desc: "Custom iron pedestrian gates, designed to integrate with existing fencing and structures." },
        { name: "Swing & folding gates", desc: "Swing and folding gates with custom design, artisan production and installation." },
        { name: "Self-supporting gates", desc: "Sliding solution without ground rail, ideal for businesses, homes and driveways with frequent traffic." },
      ],
      whyIronTitle: "Why choose ",
      whyIronAccent: "iron",
      whyIronBenefits: ["Resistance to compression and tension", "Material that holds its shape over time", "Customisable in style and type", "Wide range of finishes and treatments"],
      prontaConsegnaTitle: "Gates in ",
      prontaConsegnaAccent: "stock",
      prontaConsegnaBody: "We have a range of ready-delivery gates visible at our showroom in Palata Pepoli di Crevalcore (BO). If you need a gate urgently, we can help you choose the right solution quickly.",
      faq: [
        { q: "Do you make custom iron gates?", a: "Yes, we make fully custom iron gates designed to meet the aesthetic and functional needs of each client." },
        { q: "How much does a custom iron gate cost?", a: "The cost depends on dimensions, design, finishes and type. After a site visit we provide a precise, personalised quote." },
        { q: "Are your gates CE marked?", a: "Yes, gates are produced in compliance with current regulations, CE marked when required and supplied with necessary technical documentation." },
        { q: "Which areas do you cover?", a: "We operate in Bologna and Modena provinces, with direct site visits and installations." },
      ],
    },
    inferriate: {
      hero: {
        headline: "Custom security bars for ",
        headlineAccent: "safety and aesthetics",
        subheadline: "Production and sale of custom iron security bars, designed to increase home security without sacrificing aesthetics.",
        cta: "Request your quote",
      },
      variants: [
        { name: "Fixed bars", desc: "Ideal for windows and openings that don't require access. High protection, structural solidity and wide aesthetic customisation." },
        { name: "Opening bars", desc: "For doors, windows and French doors. Maintain security while ensuring ease of use and management." },
        { name: "Folding bars", desc: "Particularly suited for French doors and frequent passages. Space-saving with minimal visual impact." },
        { name: "Double-leaf bars", desc: "Practical solution for larger openings, customisable in finishes and seamlessly integrated into the home's style." },
      ],
      benefitsTitle: "The perfect union of ",
      benefitsAccent: "security",
      benefitsPost: " and aesthetics",
      benefits: ["Strong deterrent against break-ins", "Open windows safely for ventilation", "No electricity required", "Lasting protection over time", "Enhance the property's aesthetics", "Tax deductible"],
      faq: [
        { q: "Are security bars made to measure?", a: "Yes, all bars are custom-made to fit perfectly to existing windows, doors and openings." },
        { q: "Do you make opening security bars?", a: "Yes, we make opening bars that ensure security without sacrificing practicality and escape routes." },
        { q: "Are security bars tax deductible?", a: "Yes, installing security bars qualifies as a property security improvement and is tax deductible under current legislation." },
      ],
    },
    recinzioni: {
      hero: {
        headline: "Custom iron ",
        headlineAccent: "fencing",
        subheadline: "Sale and installation of custom iron fencing for homes, condominiums and businesses. Bespoke models and modular slats.",
        cta: "Request your quote",
      },
      ironTitle: "Iron fencing: a solution that ",
      ironAccent: "lasts",
      ironBody: "Iron is an undeformable material that withstands any temperature and weather condition, requiring minimal maintenance. By choosing us, you ensure that gate and fence follow the same ironwork design.",
      modularTitle: "Modular slats and ",
      modularAccent: "metal mesh",
      modularBody: "We also offer standard modular slat models, ideal for quick, simple fencing at a competitive price. Metal mesh is perfect for delimiting agricultural and industrial spaces with strong resistance and long life.",
      benefits: ["Security and lasting resistance", "Wide customisation options", "Coordination with existing gates", "Solutions for homes and businesses"],
      faq: [
        { q: "Do you also make modular slat fencing?", a: "Yes, we offer standard modular slat models ideal for quick and cost-effective fencing of residential and commercial spaces." },
        { q: "What finishes are available?", a: "We offer hot-dip galvanisation, powder coating in any RAL colour, or simply anti-rust primer. Each finish is chosen based on the environment and aesthetic." },
        { q: "Do you provide installation?", a: "Yes, our team takes care of surveying, production and direct installation. We do not rely on third parties." },
        { q: "Which areas do you cover?", a: "We operate mainly in Bologna and Modena provinces with direct site visits and installations." },
      ],
    },
    lavorazioni: {
      hero: {
        headline: "Other iron ",
        headlineAccent: "works",
        subheadline: "Stairs, balustrades, carports, commercial dehors and iron furniture. Every project is designed to measure for your needs.",
        cta: "Request your quote",
      },
      sections: [
        { id: "scale", name: "Iron Stairs", desc: "We design and build custom iron stairs for indoor and outdoor, residential and industrial. Straight, with landing, metal structure — combinable with wood, glass or other materials.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg" },
        { id: "balustre", name: "Balustrades & Railings", desc: "Custom balustrades and railings for balconies, stairs and terraces, compliant with safety regulations. Galvanised for long life.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/parapetti-per-balconi-1-300x225.jpg" },
        { id: "carport", name: "Carports & Canopies", desc: "Custom iron carports: self-supporting canopies to protect vehicles from the elements. Customisable and galvanised for maximum resistance.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/28f664fa9_generated_image.png" },
        { id: "dehor", name: "Commercial Dehors", desc: "Custom iron dehors for bars, restaurants and commercial activities. Resistant, elegant and fully customisable structures, compliant with local regulations.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Strutture-in-ferro-su-misura.jpg" },
        { id: "arredi", name: "Iron Furniture", desc: "Industrial and residential iron furniture: shelving, workbenches, beds, cabinets, bathroom fittings, bookcases. Everything 100% custom-made.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Arredi-in-ferro-su-misura-bologna-1-300x225.jpg" },
      ],
    },
    carport: {
      hero: {
        headline: "Custom iron ",
        headlineAccent: "carports & canopies",
        subheadline: "We design and build custom iron carports and canopies to protect your vehicles from the elements. Self-supporting structures, galvanised and paintable on request.",
        cta: "Request your quote",
      },
      introTitle: "Tailored protection for ",
      introAccent: "your vehicles",
      introBody: "An iron carport is the ideal solution for protecting your vehicle from the elements without sacrificing aesthetics. Compared to a traditional garage, it takes up less space, costs less and integrates perfectly with your garden or driveway. Every structure is designed to measure, built in our workshop and installed directly by us.",
      featuresTitle: "Why choose an iron ",
      featuresAccent: "carport",
      features: ["Self-supporting structure, no intermediate pillars", "Hot-dip galvanisation for maximum weather resistance", "Fully customisable in size, shape and finish", "Suitable for residential and industrial use", "Compatible with solar panels", "Minimal maintenance over time", "In-house production and direct installation", "Free quote within 24h"],
      typesTitle: "Types of ",
      typesAccent: "covers",
      types: [
        { name: "Single carport", desc: "Cover for a single vehicle, ideal for private homes with a driveway. Clean design integrated with existing architecture. Available in various widths and heights.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/28f664fa9_generated_image.png" },
        { name: "Double carport", desc: "Solution for two or more vehicles, perfect for families or small businesses. Robust structure with ample usable space. Option to add side panels or enclosures.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/9edc19b42_generated_image.png" },
        { name: "Industrial canopies", desc: "Custom covers for businesses, warehouses and loading/unloading areas. High resistance and guaranteed long life. Ideal for large surfaces with high structural loads.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/190366ac2_generated_image.png" },
        { name: "Outdoor canopies", desc: "Protection for entrances, terraces and outdoor areas. Elegant, customisable and weather-resistant. Also perfect for camper or motorcycle parking areas.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/d5f42817e_generated_image.png" },
      ],
      materialsTitle: "Materials and ",
      materialsAccent: "finishes",
      materials: [
        { name: "Hot-dip galvanised steel", desc: "Hot-dip galvanisation provides maximum protection against rust and weathering, with a lifespan exceeding 20 years with no maintenance." },
        { name: "Powder coating", desc: "Available in any RAL colour. Powder coating offers excellent resistance to impact and UV rays, keeping the colour unchanged over time." },
        { name: "Polycarbonate roofing", desc: "Transparent or translucent panels that allow natural light through while protecting from rain. Lightweight, resistant and insulating." },
        { name: "Corrugated sheeting", desc: "A cost-effective and robust solution for opaque roofing. High mechanical resistance and long-lasting waterproofing." },
      ],
      faq: [
        { q: "How much does a custom iron carport cost?", a: "The cost depends on dimensions, roofing type and chosen finishes. After a free site visit we provide a detailed, no-obligation quote." },
        { q: "Do I need planning permission for a carport?", a: "It depends on the dimensions and local regulations. For smaller structures a simplified notification is often sufficient. We assist you with the process." },
        { q: "How long does it take to build and install?", a: "Timelines depend on project complexity. On average, from quote confirmation to installation it takes 3-6 weeks." },
        { q: "Are carports compatible with solar panels?", a: "Yes, we design structures to accommodate photovoltaic panels, optimising the frame sizing for the additional load." },
        { q: "Which areas do you cover?", a: "We operate in Bologna and Modena provinces with direct site visits and installations." },
      ],
    },
    automazione: {
      hero: {
        headline: "Gate ",
        headlineAccent: "automation",
        headlinePost: " systems",
        subheadline: "We build and install automation systems for gates, doors and shutters. Control via remote, smartphone and smart home systems.",
        cta: "Request a consultation",
      },
      howTitle: "How an automatic ",
      howAccent: "gate",
      howBody: "An automatic gate moves via an electric motor connected to a control unit. Safety sensors detect any obstacles and movement stops automatically.",
      types: [
        { name: "Automatic swing gates", desc: "The leaves open by rotating on a pivot, generally inwards. Ideal when there is sufficient space for opening." },
        { name: "Automatic sliding gates", desc: "The moving part slides laterally along the fence. Suitable for entrances with limited space and frequent access." },
      ],
      controls: ["Remote control", "Smartphone app", "Keypad", "Smart home integration"],
      serviceTitle: "Complete ",
      serviceAccent: "service",
      serviceBody: "Technical consultation, system selection, professional installation, safety checks and after-sales support.",
    },
    percheNoi: {
      hero: {
        headline: "Forty years of ",
        headlineAccent: "iron",
        headlinePost: " crafted with care",
        subheadline: "Ferioli Sergio SRL — born from experience, grown on quality. Certified metalwork in the Bologna province.",
        cta: "Request your quote",
      },
      storyTitle: "Our ",
      storyAccent: "story",
      storyBody: "Ferioli Sergio SRL has been operating in metalwork for 49 years (1977-2026), based at Via Galileo Galilei 140, Palata Pepoli di Crevalcore (BO). We specialise in producing security bars, fencing, metal mesh, stairs, carports, dehors, iron furniture and modular and custom gates.",
      certTitle: "Certified ",
      certAccent: "first in Italy",
      certBody: "Istituto Giordano, a leading technical body in product testing, certification, research, design and training, founded in 1959, certified us first in Italy for both manual and automatic gates. Tested for 60,000 openings, we obtained CE product marking.",
      guaranteeTitle: "Our ",
      guaranteeAccent: "guarantee",
      guaranteeBody: "Every product is crafted with care for every detail, striving for perfection to meet client needs. Security, resistance and aesthetics are the three core characteristics of our work.",
    },
    realizzazioni: {
      hero: {
        headline: "Our ",
        headlineAccent: "portfolio",
        subheadline: "Every project tells a story of artisan quality, attention to detail and client satisfaction.",
        cta: "Request your quote",
      },
      projects: [
        { name: "Sliding Gate", location: "Bologna", type: "Gate", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Carpenteria-metallica-su-misura-bologna-cento.jpg", link: "/cancelli" },
        { name: "Swing Gate", location: "Cento (FE)", type: "Gate", image: "https://eurofabbro.com/wp-content/uploads/slider2/2.jpeg", link: "/cancelli" },
        { name: "Fencing", location: "Massa Finalese (MO)", type: "Fence", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Cancelli-in-ferro-cento-1-300x225.jpg", link: "/recinzioni" },
        { name: "Internal Stairs", location: "Bologna", type: "Structure", image: "https://eurofabbro.com/wp-content/uploads/2023/04/4.jpg", link: "/lavorazioni" },
        { name: "Security Bars", location: "Crevalcore (BO)", type: "Security Bars", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-grate-in-ferro-bologna-480x360-1.jpg", link: "/inferriate" },
        { name: "External Stairs", location: "San Giovanni in Persiceto (BO)", type: "Structure", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg", link: "/lavorazioni" },
        { name: "Balustrades", location: "Bologna", type: "Railing", image: "https://eurofabbro.com/wp-content/uploads/2023/04/parapetti-per-balconi-1-300x225.jpg", link: "/lavorazioni" },
        { name: "Custom Furniture", location: "Cento (FE)", type: "Furniture", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Arredi-in-ferro-su-misura-bologna-1-300x225.jpg", link: "/lavorazioni" },
        { name: "Commercial Dehors", location: "Bologna", type: "Structure", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Strutture-in-ferro-su-misura.jpg", link: "/lavorazioni" },
        { name: "Sheet Metal Gate", location: "Crevalcore (BO)", type: "Gate", image: "https://eurofabbro.com/wp-content/uploads/slider2/3.jpeg", link: "/cancelli" },
      ],
    },
    detrazioni: {
      hero: {
        headline: "Save up to ",
        headlineAccent: "50%",
        headlinePost: " with tax deductions",
        subheadline: "2026 tax deductions for gates, security bars and alarm systems. The right time to invest.",
        cta: "Request information",
      },
      bonusTitle: "Security Bonus and ",
      bonusAccent: "Renovation Bonus",
      bonusBody: "In 2026, tax relief is still available for improvements to property security. Work on gates, security bars, fencing and access control can qualify for security and renovation tax deductions.",
      eligibleTitle: "Which work may be ",
      eligibleAccent: "deductible",
      eligible: ["Installation of security bars", "Installation or replacement of gates", "Gate automation", "Fencing and access control systems", "Burglar alarms and CCTV"],
      compassTitle: "Financing and payment ",
      compassAccent: "options",
      compassBody: "To facilitate the project, we offer financing with customised instalment plans of 24, 36 or 48 months, so you can install immediately without sacrificing quality.",
      calcTitle: "Calculate your ",
      calcAccent: "savings",
      calcLabel: "Estimated project value (€)",
      calcPlaceholder: "e.g. 5000",
      calcResult36: "With Security Bonus (36%)",
      calcResult50: "With Tax Deductions (50%)",
      calcSave: "You save",
      faq: [
        { q: "Which products qualify for deductions?", a: "Gates, security bars, alarms, CCTV and all work that improves property security." },
        { q: "How do you claim the deduction?", a: "Payment must be made via speaking bank transfer and documentation retained. Our consultants can guide you." },
        { q: "Can the work be financed?", a: "Yes, we offer Compass instalment plans from 24 to 48 months to make the investment accessible." },
        { q: "Are security bars always deductible?", a: "Yes, bar installation qualifies as a security improvement and is tax deductible for both new and replacement installations." },
      ],
    },
    contatti: {
      headlinePre: "We're just ",
      headlineAccent: "around the corner",
      headlinePost: "",
      processTitle: "What happens after you contact us",
      processSteps: ["We respond within 24h", "Free site visit", "No-obligation quote"],
      form: {
        name: "Full name",
        phone: "Phone",
        email: "Email",
        type: "Type of work",
        typeOptions: ["Gate", "Security bars", "Fencing", "Stairs", "Alarm", "Automation", "Other"],
        message: "Message",
        privacy: "I accept the privacy policy and data processing",
        submit: "Send request",
        success: "Request sent successfully! We'll contact you within 24 hours.",
        error: "An error occurred. Please try again or call us.",
      },
    },
  },

  it: {
    lang: "it" as const,
    nav: {
      items: navBase,
      services: servicesBase,
      label: {
        servizi: "Servizi",
        lavorazioni: "Lavorazioni",
        cancelli: "Cancelli",
        inferriate: "Inferriate",
        recinzioni: "Recinzioni",
        altreLavorazioni: "Altre lavorazioni",
        carport: "Carport e Tettoie",
        automazione: "Automazione",
        percheNoi: "Perché noi",
        realizzazioni: "Realizzazioni",
        detrazioni: "Detrazioni",
        contatti: "Contatti",
        cta: "Richiedi preventivo",
        lavorazioniDesc: "Scale, balaustre, arredi e molto altro",
        cancelliDesc: "Scorrevoli, a battente, pedonali e automatizzati",
        inferriateDesc: "Grate su misura per ogni apertura",
        recinzioniDesc: "Ferro battuto e doghe modulari",
        carportDesc: "Coperture su misura per auto ed esterni",
        automazioneDesc: "Motori smart per ogni tipo di cancello",
        viewAllServices: "Vedi tutti i servizi",
      },
    },
    hero: {
      badge: "Certificati Istituto Giordano · CE",
      headlineLine1: "Carpenteria metallica",
      headlineLine2Pre: "",
      headlineLine2Accent: "certificata",
      headlineLine2Post: " su misura",
      subheadline: "Quarant'anni di lavorazioni in ferro nella provincia di Bologna. Produzione interna, marcatura CE, garanzia su ogni installazione.",
      ctaPrimary: "Richiedi preventivo gratuito",
      ctaSecondary: "Scopri le lavorazioni",
      stat1: "1977–2026 | 49 Anni di esperienza",
      stat2: "Certificati Istituto Giordano",
      stat3: "Preventivo gratuito in 24h",
    },
    products: {
      preLabel: "Cosa realizziamo",
      headlinePre: "Tutto ciò che puoi fare ",
      headlineAccent: "in ferro",
      subheadline: "Dalla progettazione alla posa in opera, realizziamo ogni lavoro internamente. Preventivo gratuito, consegna garantita.",
      viewAll: "Vedi tutte le lavorazioni",
      learnMore: "Scopri di più",
      items: [
        { name: "Cancelli e accessi", desc: "Accesso protetto e su misura per la tua proprietà. Cancelli scorrevoli, a battente, pedonali e automatizzati.", icon: "DoorOpen", link: "/cancelli" },
        { name: "Inferriate di sicurezza", desc: "Protezione per finestre e porte senza rinunciare all'estetica e alla luce naturale.", icon: "Grid3x3", link: "/inferriate" },
        { name: "Recinzioni", desc: "Perimetro sicuro e decorativo in ferro battuto o doghe modulari per ogni esigenza.", icon: "Fence", link: "/recinzioni" },
        { name: "Scale in ferro", desc: "Scale su misura per interni ed esterni, residenziali e industriali, resistenti nel tempo.", icon: "TrendingUp", link: "/lavorazioni#scale" },
        { name: "Carport e Tettoie", desc: "Strutture autoportanti in ferro su misura per proteggere auto e veicoli dagli agenti atmosferici.", icon: "Car", link: "/carport" },
        { name: "Automazione", desc: "Comfort e sicurezza con sistemi di automazione per cancelli e serramenti.", icon: "Settings", link: "/automazione" },
      ],
    },
    turnkey: {
      preLabel: "Valore Plus by Ferioli",
      headlinePre: "Valore Plus — ",
      headlineAccent: "Il servizio chiavi in mano",
      headlinePost: " di Ferioli",
      subheadline: "Dalla progettazione alla posa: pensiamo a tutto noi.",
      cards: [
        { title: "Progettazione", text: "Sopralluogo, misure e progetto su misura. Studiamo ogni dettaglio in base al tuo spazio, al tuo stile e alle normative vigenti.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/2a8eed53a_generated_image.png" },
        { title: "Pratiche", text: "Ti affianchiamo nella gestione della documentazione tecnica e nelle pratiche necessarie, senza che tu debba pensarci.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/81e9c3696_generated_image.png" },
        { title: "Realizzazione", text: "Produciamo e installiamo direttamente, senza intermediari. Dalla nostra officina a casa tua, con un unico interlocutore.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/a18bfad4e_generated_image.png" },
      ],
      closing: '"Un solo referente, dalla prima telefonata al cancello installato."',
    },
    authority: {
      preLabel: "Perché scegliere Eurofabbro",
      headlinePre: "L'unica carpenteria ",
      headlineAccent: "certificata",
      headlinePost: " della zona",
      body: "Grazie alla certificazione dell'Istituto Giordano — ente tecnico fondato nel 1959 — i nostri cancelli sono testati per 60.000 aperture e marchiati CE. Siamo il punto di riferimento per carpenteria metallica certificata tra Bologna e Cento.",
      certBadge: "Certificati Istituto Giordano · Marcatura CE",
      stats: [
        { number: "49", label: "Anni di attività (1977-2026)" },
        { number: "60.000", label: "Aperture testate per marcatura CE" },
        { number: "100%", label: "Produzione interna su misura" },
        { number: "24h", label: "Per ricevere il tuo preventivo" },
      ],
    },
    process: {
      preLabel: "Il nostro processo",
      headlinePre: "Dalla ",
      headlineAccent: "richiesta",
      headlinePost: " alla posa in opera",
      steps: [
        { title: "1. Contattaci", desc: "Chiamaci, scrivici su WhatsApp o compila il form. Risponderemo entro 24 ore per fissare un sopralluogo gratuito.", icon: "MessageCircle" },
        { title: "2. Sopralluogo e progetto", desc: "Veniamo da te, misuriamo e progettiamo la soluzione su misura. Ti inviamo un preventivo dettagliato senza impegno.", icon: "Ruler" },
        { title: "3. Produzione e posa", desc: "Produciamo internamente e installiamo. Garantiamo il lavoro e siamo disponibili per ogni necessità post-installazione.", icon: "CheckCircle" },
      ],
    },
    featuredProjects: {
      preLabel: "I nostri lavori",
      headlinePre: "Ogni ",
      headlineAccent: "lavorazione",
      headlinePost: " racconta una storia",
      viewAll: "Vedi tutte le realizzazioni",
      projects: [
        { name: "Cancello Autoportante", location: "Bologna", image: "https://eurofabbro.com/wp-content/uploads/slider2/1.jpeg", link: "/cancelli" },
        { name: "Inferriate di Sicurezza", location: "Cento (FE)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/5.jpg", link: "/inferriate" },
        { name: "Scale e Strutture", location: "Crevalcore (BO)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg", link: "/lavorazioni" },
        { name: "Cancello a Battente", location: "San Giovanni in Persiceto (BO)", image: "https://eurofabbro.com/wp-content/uploads/slider2/2.jpeg", link: "/cancelli" },
        { name: "Recinzioni su Misura", location: "Massa Finalese (MO)", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Cancelli-in-ferro-cento-1-300x225.jpg", link: "/recinzioni" },
        { name: "Grate Antieffrazione", location: "Bologna", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-grate-in-ferro-bologna-480x360-1.jpg", link: "/inferriate" },
      ],
    },
    deductionBanner: {
      headlinePre: "Risparmia fino al ",
      headlineAccent: "50%",
      headlinePost: " con le detrazioni fiscali",
      body: "Il Bonus Sicurezza ti permette di detrarre il 36% delle spese per cancelli, inferriate e sistemi di sicurezza. Con le detrazioni fiscali si arriva al 50%. Finanziamento a tasso agevolato con Compass, rate da 24 a 48 mesi.",
      cta: "Scopri come risparmiare",
      badges: ["Bonus Sicurezza 36%", "Detrazione 50%", "Compass 24/36/48 mesi"],
    },
    testimonials: {
      preLabel: "Dicono di noi",
      headlinePre: "La ",
      headlineAccent: "fiducia",
      headlinePost: " dei nostri clienti",
      items: [
        { quote: "Lavoro impeccabile sul nostro cancello scorrevole. Professionali, puntuali e il risultato ha superato le aspettative. Consigliatissimi.", name: "Marco R.", location: "Crevalcore (BO)", rating: 5 },
        { quote: "Abbiamo fatto realizzare le inferriate per tutta la casa. Qualità eccellente, installazione rapida e pulizia sul cantiere. Molto soddisfatti.", name: "Laura B.", location: "Cento (FE)", rating: 5 },
        { quote: "Ci siamo affidati a Ferioli per le recinzioni del capannone. Prezzo giusto, lavoro solido e duraturo. Li raccomandiamo senza riserve.", name: "Giovanni P.", location: "San Giovanni in Persiceto (BO)", rating: 5 },
      ],
    },
    cta: {
      preLabel: "Inizia oggi",
      headlinePre: "Richiedi il tuo preventivo ",
      headlineAccent: "gratuito",
      subheadline: "Sopralluogo gratuito, preventivo senza impegno. Rispondiamo entro 24 ore.",
      btnForm: "Compila il form",
      btnWhatsapp: "Scrivici su WhatsApp",
      btnPhone: "051 985300",
      reassurance: ["Risposta entro 24 ore", "Sopralluogo gratuito", "Preventivo senza impegno"],
    },
    workWithUs: {
      preLabel: "Collabora con noi",
      headlinePre: "Cerchiamo ",
      headlineAccent: "partner",
      headlinePost: " e professionisti",
      subheadline: "Unisciti alla nostra rete. Siamo sempre alla ricerca di installatori, rivenditori e professionisti qualificati.",
      cta: "Scopri di più",
    },
    footer: {
      tagline: "Carpenteria metallica certificata dal 1984.",
      colLavorazioni: "Lavorazioni",
      colContatti: "Contatti",
      colCertificazioni: "Certificazioni",
      certText: "Certificati Istituto Giordano · Marcatura CE",
      compassText: "Finanziamenti Compass disponibili",
      copyright: "© 2024 Ferioli Sergio SRL",
      privacy: "Privacy Policy",
      cookie: "Preferenze cookie",
      piva: "P.IVA 02128491202",
    },
    form: {
      name: "Nome completo",
      email: "Email",
      phone: "Telefono",
      message: "Come possiamo aiutarti?",
      privacy: "Inviando accetti la",
      privacyLink: "privacy policy",
      send: "Invia richiesta",
      sent: "Richiesta inviata",
      success: "Grazie! Ti ricontatteremo entro 24 ore.",
      error: "Qualcosa è andato storto. Chiamaci direttamente.",
    },
    cancelli: {
      hero: {
        headline: "Cancelli su misura e ",
        headlineAccent: "pronta consegna",
        subheadline: "Produciamo e vendiamo cancelli di qualsiasi tipologia. Soluzioni su misura basate sulle esigenze del cliente, garanzia qualità ed estetica superiori.",
        cta: "Richiedi il tuo preventivo",
      },
      variantsTitle: "Ogni ",
      variantsTitleAccent: "tipologia",
      variantsTitlePost: " su misura",
      variants: [
        { name: "Cancelli scorrevoli", desc: "Cancelli scorrevoli tradizionali con guida a terra, sospesi e autoportanti senza guida. Zincati e verniciabili su richiesta." },
        { name: "Cancelli pedonali", desc: "Cancelli pedonali in ferro su misura, progettati per integrarsi con recinzioni e strutture esistenti." },
        { name: "Cancelli a battente e a libro", desc: "Cancelli ad anta battente e a libro con progettazione personalizzata, realizzazione artigianale e installazione." },
        { name: "Cancelli autoportanti", desc: "Soluzione scorrevole senza guida a terra, ideale per aziende, abitazioni e ingressi carrabili con passaggi frequenti." },
      ],
      whyIronTitle: "Perché scegliere il ",
      whyIronAccent: "ferro",
      whyIronBenefits: ["Resistenza alla compressione e alle trazioni", "Materiale indeformabile nel tempo", "Personalizzabile per stile e tipologia", "Vasta gamma di finiture e trattamenti"],
      prontaConsegnaTitle: "Cancelli in ",
      prontaConsegnaAccent: "pronta consegna",
      prontaConsegnaBody: "Disponiamo di una gamma di cancelli in pronta consegna, visibili presso la nostra mostra espositiva a Palata Pepoli di Crevalcore (BO). Se hai bisogno urgente di un cancello, possiamo aiutarti a scegliere rapidamente la soluzione più adatta.",
      faq: [
        { q: "Realizzate cancelli in ferro su misura?", a: "Sì, realizziamo cancelli in ferro completamente su misura, progettati in base alle esigenze estetiche e funzionali del cliente." },
        { q: "Quanto costa un cancello in ferro su misura?", a: "Il costo dipende da dimensioni, design, finiture e tipologia. Dopo un sopralluogo forniamo un preventivo preciso e personalizzato." },
        { q: "I cancelli rispettano le normative e sono marcati CE?", a: "Sì, i cancelli vengono realizzati nel rispetto delle normative vigenti, marcati CE quando previsto e forniti con la documentazione tecnica necessaria." },
        { q: "In quali zone operate?", a: "Operiamo a Bologna e provincia, Modena e provincia, con sopralluoghi e installazioni dirette sul territorio." },
      ],
    },
    inferriate: {
      hero: {
        headline: "Inferriate su misura per ",
        headlineAccent: "sicurezza ed estetica",
        subheadline: "Produzione e vendita di inferriate in ferro su misura, progettate per aumentare la sicurezza dell'abitazione senza rinunciare all'estetica.",
        cta: "Richiedi il tuo preventivo",
      },
      variants: [
        { name: "Inferriate fisse", desc: "Ideali per finestre e aperture che non richiedono passaggio. Elevata protezione, solidità strutturale e ampia personalizzazione estetica." },
        { name: "Inferriate apribili", desc: "Per porte, finestre e portefinestre. Mantengono la sicurezza garantendo praticità di utilizzo e facilità di gestione." },
        { name: "Inferriate snodabili", desc: "Indicate per portefinestre e passaggi frequenti. Occupano poco spazio con impatto estetico contenuto." },
        { name: "Inferriate a due ante", desc: "Soluzione pratica per aperture di dimensioni maggiori, personalizzabili nelle finiture e integrabili nello stile dell'abitazione." },
      ],
      benefitsTitle: "La perfetta unione tra ",
      benefitsAccent: "sicurezza",
      benefitsPost: " ed estetica",
      benefits: ["Forte deterrente contro furti e intrusioni", "Finestre aperte in sicurezza per ventilazione", "Non richiedono alimentazione elettrica", "Protezione duratura nel tempo", "Contribuiscono all'estetica dell'immobile", "Fiscalmente detraibili"],
      faq: [
        { q: "Le inferriate sono realizzate su misura?", a: "Sì, tutte le inferriate vengono realizzate su misura per adattarsi perfettamente a finestre, porte e aperture esistenti." },
        { q: "Esistono inferriate apribili?", a: "Sì, realizziamo inferriate apribili che garantiscono sicurezza senza rinunciare alla praticità e alle vie di fuga." },
        { q: "Le inferriate sono detraibili fiscalmente?", a: "Sì, l'installazione delle inferriate rientra negli interventi di sicurezza dell'immobile ed è detraibile fiscalmente secondo la normativa vigente." },
      ],
    },
    recinzioni: {
      hero: {
        headline: "Recinzioni in ferro ",
        headlineAccent: "su misura",
        subheadline: "Vendita e installazione di recinzioni in ferro personalizzate per abitazioni, condomini e aziende. Modelli su misura e doghe modulari.",
        cta: "Richiedi il tuo preventivo",
      },
      ironTitle: "Recinzioni in ferro: una soluzione che ",
      ironAccent: "dura nel tempo",
      ironBody: "Il ferro è un materiale indeformabile nel tempo, resistente a qualsiasi temperatura e condizione climatica, che richiede una manutenzione minima. Affidandoti a noi, ti assicurerai che cancello e recinzione seguano lo stesso disegno di lavorazione del ferro.",
      modularTitle: "Doghe modulari e ",
      modularAccent: "reti metalliche",
      modularBody: "Disponiamo anche di modelli standard a doghe modulari, ideali per recintare in modo semplice, veloce e a un prezzo conveniente. Le reti metalliche sono perfette per delimitare spazi agricoli e industriali con forte resistenza e lunga durata.",
      benefits: ["Sicurezza e resistenza nel tempo", "Ampia possibilità di personalizzazione", "Coordinamento con cancelli esistenti", "Soluzioni per privati e aziende"],
      faq: [
        { q: "Realizzate anche recinzioni a doghe modulari?", a: "Sì, offriamo modelli standard a doghe modulari, ideali per recintare in modo rapido e conveniente spazi residenziali e commerciali." },
        { q: "Quali finiture sono disponibili?", a: "Offriamo zincatura a caldo, verniciatura a polvere in qualsiasi colore RAL, o semplice antiruggine. Ogni finitura è scelta in base all'ambiente e all'estetica." },
        { q: "Fornite anche l'installazione?", a: "Sì, il nostro team si occupa di rilievo, produzione e installazione diretta. Non ci affidiamo a terzi." },
        { q: "Quali zone coprite?", a: "Operiamo principalmente nelle province di Bologna e Modena con sopralluoghi e installazioni dirette." },
      ],
    },
    lavorazioni: {
      hero: {
        headline: "Altre lavorazioni in ",
        headlineAccent: "ferro",
        subheadline: "Scale, balaustre, carport, dehor commerciali e arredi in ferro. Ogni progetto è studiato su misura per le tue esigenze.",
        cta: "Richiedi il tuo preventivo",
      },
      sections: [
        { id: "scale", name: "Scale in ferro", desc: "Progettiamo e realizziamo scale in ferro su misura per interni ed esterni, sia residenziali che industriali. Scale dritte, con pianerottolo, a struttura metallica — combinabili con legno, vetro o altri materiali.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg" },
        { id: "balustre", name: "Balaustre e ringhiere", desc: "Realizziamo balaustre e ringhiere personalizzate per balconi, scale e terrazzi, nel rispetto delle normative di sicurezza. Parapetti e corrimano sia per interni che per esterni, con trattamento di zincatura per lunga durata.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/parapetti-per-balconi-1-300x225.jpg" },
        { id: "carport", name: "Carport e tettoie", desc: "Realizziamo carport in ferro su misura: tettoie e pensiline autoportanti per proteggere auto e veicoli dagli agenti atmosferici. Personalizzabili e zincati per massima resistenza.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/28f664fa9_generated_image.png" },
        { id: "dehor", name: "Dehor commerciali", desc: "Dehor su misura in ferro per bar, ristoranti e attività commerciali. Strutture resistenti, eleganti e personalizzabili a 360 gradi, nel rispetto delle normative comunali.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Strutture-in-ferro-su-misura.jpg" },
        { id: "arredi", name: "Arredi in ferro", desc: "Produzione di arredi in ferro sia industriali che per la casa: scaffalature, banchi di lavoro, letti, mobili, arredo bagno, librerie. Tutto personalizzabile al 100% su misura.", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Arredi-in-ferro-su-misura-bologna-1-300x225.jpg" },
      ],
    },
    carport: {
      hero: {
        headline: "Carport e tettoie in ",
        headlineAccent: "ferro su misura",
        subheadline: "Realizziamo carport e pensiline in ferro personalizzate per proteggere auto e veicoli dagli agenti atmosferici. Strutture autoportanti, zincate e verniciabili su richiesta.",
        cta: "Richiedi il tuo preventivo",
      },
      introTitle: "Protezione su misura per ",
      introAccent: "la tua auto",
      introBody: "Un carport in ferro è la soluzione ideale per chi vuole proteggere il proprio veicolo dagli agenti atmosferici senza rinunciare all'estetica. Rispetto a un garage tradizionale, occupa meno spazio, costa meno e si integra perfettamente con il giardino o il vialetto d'accesso. Ogni struttura è progettata su misura, costruita nel nostro laboratorio e installata direttamente da noi.",
      featuresTitle: "Perché scegliere un carport in ",
      featuresAccent: "ferro",
      features: ["Struttura autoportante senza pilastri intermedi", "Zincatura a caldo per massima resistenza alle intemperie", "Personalizzabile in dimensioni, forme e finiture", "Adatto a uso residenziale e industriale", "Compatibile con pannelli fotovoltaici", "Manutenzione minima nel tempo", "Produzione interna e installazione diretta", "Preventivo gratuito entro 24h"],
      typesTitle: "Tipologie di ",
      typesAccent: "coperture",
      types: [
        { name: "Carport singolo", desc: "Copertura per un singolo veicolo, ideale per abitazioni private con accesso carrabile. Design pulito e integrato con l'architettura esistente. Disponibile in varie larghezze e altezze.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/28f664fa9_generated_image.png" },
        { name: "Carport doppio", desc: "Soluzione per due o più veicoli, perfetta per famiglie o piccole attività. Struttura robusta con ampio spazio utile. Possibilità di aggiungere pareti laterali o pannelli di chiusura.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/9edc19b42_generated_image.png" },
        { name: "Pensiline industriali", desc: "Coperture su misura per aziende, magazzini e aree di carico/scarico. Alta resistenza e lunga durata garantita. Ideali per grandi superfici con alta portata strutturale.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/190366ac2_generated_image.png" },
        { name: "Tettoie per esterni", desc: "Protezione per ingressi, terrazzi e aree esterne. Eleganti, personalizzabili e resistenti alle intemperie. Perfette anche per proteggere aree di sosta camper o moto.", image: "https://media.base44.com/images/public/69baf22d9cc002736b6b7248/d5f42817e_generated_image.png" },
      ],
      materialsTitle: "Materiali e ",
      materialsAccent: "finiture",
      materials: [
        { name: "Ferro zincato a caldo", desc: "La zincatura a caldo garantisce la massima protezione dalla ruggine e dagli agenti atmosferici, con una durata superiore a 20 anni senza manutenzione." },
        { name: "Verniciatura a polvere", desc: "Disponibile in qualsiasi colore RAL. La verniciatura a polvere offre un'ottima resistenza agli urti e ai raggi UV, mantenendo il colore invariato nel tempo." },
        { name: "Coperture in policarbonato", desc: "Pannelli trasparenti o traslucidi che lasciano passare la luce naturale pur proteggendo dalla pioggia. Leggeri, resistenti e isolanti." },
        { name: "Lamiera grecata", desc: "Soluzione economica e robusta per coperture opache. Alta resistenza meccanica e impermeabilità garantita nel tempo." },
      ],
      faq: [
        { q: "Quanto costa un carport in ferro su misura?", a: "Il costo varia in base alle dimensioni, alla tipologia di copertura e alle finiture scelte. Dopo un sopralluogo gratuito ti forniamo un preventivo dettagliato e senza impegno." },
        { q: "È necessario il permesso edilizio per installare un carport?", a: "Dipende dalle dimensioni e dal comune di riferimento. Per strutture di piccole dimensioni spesso è sufficiente la CILA. Vi assistiamo nell'iter burocratico." },
        { q: "In quanto tempo viene realizzato e installato?", a: "I tempi dipendono dalla complessità del progetto. Mediamente, dalla conferma del preventivo all'installazione passano 3-6 settimane." },
        { q: "I carport sono compatibili con pannelli solari?", a: "Sì, progettiamo le strutture per accogliere pannelli fotovoltaici, ottimizzando il dimensionamento dei profilati per la portata aggiuntiva." },
        { q: "Operate in tutta la provincia di Bologna?", a: "Operiamo nelle province di Bologna e Modena con sopralluoghi e installazioni dirette." },
      ],
    },
    automazione: {
      hero: {
        headline: "Sistemi di ",
        headlineAccent: "automazione",
        headlinePost: " per cancelli",
        subheadline: "Realizziamo e installiamo sistemi di automazione per cancelli, porte e serramenti. Controllo tramite telecomando, smartphone e sistemi domotici.",
        cta: "Richiedi consulenza",
      },
      howTitle: "Come funziona un cancello ",
      howAccent: "automatico",
      howBody: "Un cancello automatico si muove grazie a un motore elettrico collegato a una centralina di controllo. I sensori di sicurezza rilevano eventuali ostacoli e il movimento si arresta automaticamente.",
      types: [
        { name: "Cancelli automatici a battente", desc: "Le ante si aprono ruotando su un perno, generalmente verso l'interno. Ideali quando c'è spazio sufficiente per l'apertura." },
        { name: "Cancelli automatici scorrevoli", desc: "La parte mobile scorre lateralmente lungo la recinzione. Adatti per ingressi con spazio limitato e accessi frequenti." },
      ],
      controls: ["Telecomando", "Smartphone con app dedicata", "Tastiera di comando", "Sistemi domotici integrati"],
      serviceTitle: "Servizio ",
      serviceAccent: "completo",
      serviceBody: "Consulenza tecnica, scelta del sistema più adatto, installazione professionale, verifiche di sicurezza e assistenza post installazione.",
    },
    percheNoi: {
      hero: {
        headline: "Quarant'anni di ",
        headlineAccent: "ferro",
        headlinePost: " lavorato con cura",
        subheadline: "Ferioli Sergio SRL — nata dall'esperienza, cresciuta sulla qualità. Carpenteria metallica certificata nella provincia di Bologna.",
        cta: "Richiedi il tuo preventivo",
      },
      storyTitle: "La nostra ",
      storyAccent: "storia",
      storyBody: "Ferioli Sergio SRL opera nel settore della carpenteria metallica da 49 anni (1977-2026), con sede in Via Galileo Galilei 140, Palata Pepoli di Crevalcore (BO). Siamo specializzati nella produzione di grate di sicurezza, recinzioni, reti metalliche, scale, carport, dehor, arredi in ferro e cancelli modulari e su misura.",
      certTitle: "Certificati ",
      certAccent: "primi in Italia",
      certBody: "L'Istituto Giordano, ente tecnico all'avanguardia nel testing di prodotto, certificazione, ricerca, progettazione e formazione, fondato nel 1959, ci ha certificati primi in Italia sia per cancelli manuali che automatici. Testati per 60.000 aperture, abbiamo ottenuto la marcatura CE dei prodotti.",
      guaranteeTitle: "La nostra ",
      guaranteeAccent: "garanzia",
      guaranteeBody: "Ogni nostro prodotto è realizzato curando ogni minimo dettaglio e cercando di renderlo perfetto per le esigenze del cliente. Sicurezza, resistenza ed estetica sono le tre principali caratteristiche delle nostre realizzazioni.",
    },
    realizzazioni: {
      hero: {
        headline: "Le nostre ",
        headlineAccent: "realizzazioni",
        subheadline: "Ogni progetto racconta una storia di qualità artigianale, attenzione al dettaglio e soddisfazione del cliente.",
        cta: "Richiedi il tuo preventivo",
      },
      projects: [
        { name: "Cancello Scorrevole", location: "Bologna", type: "Cancello", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Carpenteria-metallica-su-misura-bologna-cento.jpg", link: "/cancelli" },
        { name: "Cancello a Battente", location: "Cento (FE)", type: "Cancello", image: "https://eurofabbro.com/wp-content/uploads/slider2/2.jpeg", link: "/cancelli" },
        { name: "Recinzioni", location: "Massa Finalese (MO)", type: "Recinzione", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Cancelli-in-ferro-cento-1-300x225.jpg", link: "/recinzioni" },
        { name: "Scala Interna", location: "Bologna", type: "Struttura", image: "https://eurofabbro.com/wp-content/uploads/2023/04/4.jpg", link: "/lavorazioni" },
        { name: "Grate Antieffrazione", location: "Crevalcore (BO)", type: "Inferriata", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-grate-in-ferro-bologna-480x360-1.jpg", link: "/inferriate" },
        { name: "Scala Esterna", location: "San Giovanni in Persiceto (BO)", type: "Struttura", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Realizzazione-strutture-in-ferro-cento-480x360-1.jpg", link: "/lavorazioni" },
        { name: "Balaustra e Parapetto", location: "Bologna", type: "Ringhiera", image: "https://eurofabbro.com/wp-content/uploads/2023/04/parapetti-per-balconi-1-300x225.jpg", link: "/lavorazioni" },
        { name: "Arredi su Misura", location: "Cento (FE)", type: "Arredo", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Arredi-in-ferro-su-misura-bologna-1-300x225.jpg", link: "/lavorazioni" },
        { name: "Dehor Commerciale", location: "Bologna", type: "Struttura", image: "https://eurofabbro.com/wp-content/uploads/2023/04/Strutture-in-ferro-su-misura.jpg", link: "/lavorazioni" },
        { name: "Cancello in Lamiera", location: "Crevalcore (BO)", type: "Cancello", image: "https://eurofabbro.com/wp-content/uploads/slider2/3.jpeg", link: "/cancelli" },
      ],
    },
    detrazioni: {
      hero: {
        headline: "Risparmia fino al ",
        headlineAccent: "50%",
        headlinePost: " grazie alle detrazioni fiscali",
        subheadline: "Detrazioni fiscali 2026 per cancelli, inferriate e sistemi di sicurezza. Il momento giusto per intervenire.",
        cta: "Richiedi informazioni",
      },
      bonusTitle: "Bonus Sicurezza e ",
      bonusAccent: "Bonus Ristrutturazioni",
      bonusBody: "Nel 2026 sono ancora previste agevolazioni fiscali per interventi che migliorano la sicurezza degli immobili. Gli interventi su cancelli, grate di sicurezza, recinzioni e sistemi di controllo accessi possono rientrare nelle detrazioni fiscali per la sicurezza e la ristrutturazione edilizia.",
      eligibleTitle: "Quali interventi possono essere ",
      eligibleAccent: "detraibili",
      eligible: ["Installazione di inferriate di sicurezza", "Installazione o rifacimento di cancelli", "Automazione dei cancelli", "Recinzioni e sistemi di controllo accessi", "Sistemi antifurto e videosorveglianza"],
      compassTitle: "Finanziamenti e soluzioni di ",
      compassAccent: "pagamento",
      compassBody: "Per facilitare l'intervento, offriamo la possibilità di accedere a finanziamenti con piani rateali personalizzati da 24, 36 o 48 mesi, così da installare subito senza rinunciare alla qualità.",
      calcTitle: "Calcola il tuo ",
      calcAccent: "risparmio",
      calcLabel: "Valore indicativo del progetto (€)",
      calcPlaceholder: "es. 5000",
      calcResult36: "Con il Bonus Sicurezza (36%)",
      calcResult50: "Con le detrazioni (50%)",
      calcSave: "Risparmi",
      faq: [
        { q: "Quali prodotti rientrano nelle detrazioni?", a: "Cancelli, inferriate, sistemi di allarme, videosorveglianza e tutti gli interventi che migliorano la sicurezza dell'immobile." },
        { q: "Come si ottiene la detrazione?", a: "È necessario effettuare il pagamento tramite bonifico parlante e conservare la documentazione. I nostri consulenti possono guidarvi." },
        { q: "È possibile finanziare il lavoro?", a: "Sì, offriamo piani rateali con Compass da 24 a 48 mesi per rendere l'investimento accessibile." },
        { q: "Le inferriate sono sempre detraibili?", a: "Sì, l'installazione delle inferriate rientra negli interventi di sicurezza ed è fiscalmente detraibile sia per nuove installazioni che per sostituzioni." },
      ],
    },
    contatti: {
      headlinePre: "Siamo a ",
      headlineAccent: "due passi",
      headlinePost: " da te",
      processTitle: "Cosa succede dopo che ci contatti",
      processSteps: ["Risponderemo entro 24h", "Sopralluogo gratuito", "Preventivo senza impegno"],
      form: {
        name: "Nome e cognome",
        phone: "Telefono",
        email: "Email",
        type: "Tipo di lavoro",
        typeOptions: ["Cancello", "Inferriata", "Recinzione", "Scala", "Allarme", "Automazione", "Altro"],
        message: "Messaggio",
        privacy: "Accetto la privacy policy e il trattamento dei dati personali",
        submit: "Invia richiesta",
        success: "Richiesta inviata con successo! Ti contatteremo entro 24 ore.",
        error: "Si è verificato un errore. Riprova o contattaci telefonicamente.",
      },
    },
  },
} as const;

export type Lang = keyof typeof translations;
export type T = (typeof translations)[Lang];
